/** D-178 S1 — how `build-binary.mjs` reaches postject, and what it refuses.
 *
 *  Both properties below were found by running the build on a Windows arm64 host
 *  and neither was pinned by anything. The Linux path goes through Docker with an
 *  official Node image, so it never exercised either one.
 *
 *  This asserts on the SCRIPT SOURCE rather than by running it, because running
 *  it needs a Node with a SEA fuse sentinel — which the CI host may not have, and
 *  which is itself one of the things under test. Source assertions are weaker
 *  than execution, so each one below names the exact failure it prevents.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

const SCRIPT = join(dirname(fileURLToPath(import.meta.url)), '../../scripts/build-binary.mjs');
const source = readFileSync(SCRIPT, 'utf8');

/** Comments discuss npx at length — deliberately, since the point is why NOT to
 *  use it. Only executable lines can regress. */
const code = source
  .split('\n')
  .filter((line) => !/^\s*(\/\/|\*|\/\*)/.test(line))
  .join('\n');

describe('build-binary reaches postject without npx', () => {
  it('⛔ never spawns npx — it is npx.cmd on Windows, which Node refuses', () => {
    // Bare 'npx' fails ENOENT on Windows (npm ships .cmd shims); 'npx.cmd' then
    // fails EINVAL, because Node will not spawn a .cmd without `shell: true`
    // since the CVE-2024-27980 hardening. Both were measured on a Windows arm64
    // host, and both surfaced as "install postject" — pointing at the wrong
    // component entirely.
    expect(code).not.toMatch(/['"`]npx(\.cmd)?['"`]/);
  });

  it('⛔ never fetches the injector from the network at build time', () => {
    // `npx --yes postject` resolved an UNPINNED package and let it write into a
    // binary we then sign. postject is a devDependency so the injector is in the
    // lockfile like everything else, and an offline build works.
    expect(code).not.toMatch(/--yes/);
    const pkg = JSON.parse(
      readFileSync(join(dirname(SCRIPT), '../package.json'), 'utf8'),
    ) as { devDependencies?: Record<string, string> };
    expect(pkg.devDependencies?.postject).toBeTruthy();
  });

  it('runs the injector with THIS node, resolved through package.json', () => {
    // process.execPath is the same runtime the rest of the build used. Resolving
    // the bin through package.json rather than hardcoding dist/cli.js means an
    // upstream layout change fails loudly here instead of silently skipping
    // injection.
    expect(code).toMatch(/execFileSync\(\s*\n?\s*process\.execPath/);
    expect(code).toMatch(/resolve\(\s*['"`]postject\/package\.json['"`]\s*\)/);
    expect(code).toMatch(/\.bin\.postject/);
  });
});

describe('build-binary refuses a Node that cannot host a SEA', () => {
  it('⛔ checks for the fuse sentinel BEFORE injecting', () => {
    // Not every `node` can be a SEA base: injection needs the fuse sentinel
    // compiled in, and homebrew/distro builds omit it. Measured — homebrew node
    // 25.9.0 contains zero occurrences, official node:24 contains one. Without
    // this, postject fails with "could not find the sentinel", which reads as a
    // corrupt build rather than the wrong runtime.
    // Anchored on 'NODE_SEA_BLOB', which appears ONLY in the postject argv.
    // Neither `execFileSync` nor `process.execPath` discriminates: the SEA blob
    // is generated by `execFileSync(process.execPath, ['--experimental-sea-
    // config', …])` EARLIER in the file, so both anchors resolve to that call
    // and the ordering assertion passes — or fails — for the wrong reason.
    const guard = code.indexOf('SEA fuse sentinel');
    const inject = code.indexOf('NODE_SEA_BLOB');
    expect(guard).toBeGreaterThan(-1);
    expect(inject).toBeGreaterThan(-1);
    expect(guard).toBeLessThan(inject);
  });

  it('names the fix in the message, since the raw postject error misdirects', () => {
    expect(source).toMatch(/nodejs\.org/);
  });
});
