/** D-148 § A.5.3 / § A.6.5 — Node-side PKCS#10 CSR emitter for Ed25519.
 *
 *  Sole production implementation of the `generateCsr` seam consumed by
 *  `createAcmeDomainRenewer` (per-domain renewer, D-148 § A.6.5). Emits
 *  a PEM-wrapped `CertificationRequest` (RFC 2986) carrying a
 *  Subject (CN=<domain>) + Subject Alternative Name (DNS:<domain>) +
 *  Ed25519 SubjectPublicKeyInfo (RFC 8410) + Ed25519 signature over
 *  the `CertificationRequestInfo` DER.
 *
 *  Hand-rolled ASN.1 / DER. The alternative was a `node-forge`
 *  dependency, rejected because (a) forge's Ed25519 CSR support
 *  requires the same manual SPKI + signing detour we'd write here
 *  anyway, (b) forge adds a ~1 MB transitive surface for a 150-line
 *  capability we already have via `node:crypto`, (c) every byte we
 *  sign should be controlled by code we audit. The encoding is
 *  straightforward DER per RFC 5280 / RFC 8410 / RFC 2986:
 *
 *      CertificationRequest ::= SEQUENCE {
 *        certificationRequestInfo CertificationRequestInfo,
 *        signatureAlgorithm       AlgorithmIdentifier,
 *        signature                BIT STRING
 *      }
 *
 *      CertificationRequestInfo ::= SEQUENCE {
 *        version       INTEGER { v1(0) },
 *        subject       Name,
 *        subjectPKInfo SubjectPublicKeyInfo,
 *        attributes    [0] IMPLICIT Attributes
 *      }
 *
 *      AlgorithmIdentifier ::= SEQUENCE { algorithm OID }  -- Ed25519: 1.3.101.112
 *
 *  The CSR carries a SAN extension with one `dNSName` entry matching
 *  the Subject CN. The cloud `/v1/acme/issue-cert` Worker validates
 *  the CSR's CN + SAN both against the requested full Pro DDNS `domain`
 *  (e.g. `<handle>.recued.net`, D-176) — both must be present for the
 *  Worker to accept (§ A.5.3 helper contract).
 *
 *  Key-class discipline (D-148 I-4 / I-5). The function accepts a
 *  PEM-serialized `tls_private_key` and uses `node:crypto` primitives
 *  directly — it never instantiates the `Ed25519Keypair` shape and
 *  never invokes `assertKeyCapable`. `tls_private_key`'s capability is
 *  `tls_internal` (per `KEY_CAPABILITIES`); CSR generation IS the TLS-
 *  internal operation. The signing primitive here is the same Ed25519
 *  routine `ed25519Sign` uses, but the wrapping discipline differs by
 *  key class: TLS keys never cross the application boundary as a
 *  signing handle.
 *
 *  Algorithm scope = Ed25519 only (deliberate; matches the per-domain
 *  renewer's `pro_acme` source contract). The `tls_domains` upload
 *  path admits RSA + ECDSA for `byo_upload` rows (per § A.6.3:
 *  "Private key must form a valid pair with the cert — RSA / ECDSA
 *  verification"); those rows don't flow through this emitter. The
 *  renewer (`createAcmeDomainRenewer`) filters at `extractHandleStem`
 *  — any row whose `domain` isn't a single-label handle of an enabled
 *  Pro DDNS zone (e.g. `<single-label>.recued.net`) returns
 *  `helper_unavailable` BEFORE the CSR call. BYO domains are
 *  user-managed (certbot / Caddy on the user's side); Pro DDNS
 *  domains are server-generated by `tls_private_key` provisioning
 *  which uses Ed25519 (the only algorithm the rotation engine emits
 *  for this key class, per `keys/rotation/index.ts:572-615`). A non-
 *  Ed25519 key reaching this function is therefore a substrate-
 *  posture mismatch — surface as `KEY_NOT_ED25519` so the operator
 *  hits Settings → Server → TLS rather than an opaque CSR-emit
 *  failure deep in the renewer.
 *
 *  Spec: D-148 § A.5.3 (CSR-only ACME flow) + § A.6.5
 *  (per-domain renewer seam). */

import {
  createPrivateKey,
  createPublicKey,
  sign as nodeSign,
} from 'node:crypto';

/** Closed-list error codes the emitter throws on. Surface for log
 *  consumers + the renewer's `helper_unavailable` mapping; the renewer
 *  wraps every call in `try/catch` so any throw maps to a closed-list
 *  reason without leaking the underlying message. */
export const GENERATE_CSR_ERRORS = {
  EMPTY_DOMAIN: 'generate_csr_empty_domain',
  DOMAIN_NOT_ASCII: 'generate_csr_domain_not_ascii',
  DOMAIN_TOO_LONG: 'generate_csr_domain_too_long',
  KEY_PARSE_FAILED: 'generate_csr_key_parse_failed',
  KEY_NOT_ED25519: 'generate_csr_key_not_ed25519',
  SPKI_EXPORT_FAILED: 'generate_csr_spki_export_failed',
} as const;

/** RFC 1035 cap on a single FQDN. Defensive; the renewer's domain
 *  comes from `tls_domains.domain` which is already validated upstream
 *  at upload time, but we don't trust transitive constraints here. */
const MAX_DOMAIN_LENGTH = 253;

/** RFC 8410 OID for Ed25519. Used in the algorithm identifier slot
 *  for both `signatureAlgorithm` (outer) and (implicitly, via Node's
 *  SPKI export) inside `SubjectPublicKeyInfo`. */
const ED25519_OID = '1.3.101.112';

/** RFC 5280 OID for subject `commonName` attribute. */
const COMMON_NAME_OID = '2.5.4.3';

/** RFC 5280 OID for the SubjectAltName extension. */
const SUBJECT_ALT_NAME_OID = '2.5.29.17';

/** RFC 2985 OID for the `extensionRequest` attribute carrying X.509v3
 *  extensions in a CSR. */
const EXTENSION_REQUEST_OID = '1.2.840.113549.1.9.14';

/** ASCII-only check. The cloud ACME helper rejects internationalized
 *  domains in the CN/SAN match — callers needing punycode must
 *  convert before invoking this function. */
const ASCII_ONLY = /^[\x21-\x7e]+$/;

/** Build a PKCS#10 CSR for the given domain backed by an Ed25519
 *  private key. Returns a PEM string starting with the
 *  `-----BEGIN CERTIFICATE REQUEST-----` block. The function NEVER
 *  embeds the private key in its output — the CSR carries only the
 *  public half + a signature.
 *
 *  Shape matches the `AcmeDomainRenewerOptions.generateCsr` seam from
 *  `acme-domain-renewer.ts` directly: `{ domain, private_key_pem } =>
 *  string`. */
export const generateCsr = (args: {
  domain: string;
  private_key_pem: string;
}): string => {
  const { domain, private_key_pem } = args;

  // ── Input validation ─────────────────────────────────────────────
  if (domain.length === 0) {
    throw new Error(GENERATE_CSR_ERRORS.EMPTY_DOMAIN);
  }
  if (domain.length > MAX_DOMAIN_LENGTH) {
    throw new Error(GENERATE_CSR_ERRORS.DOMAIN_TOO_LONG);
  }
  if (!ASCII_ONLY.test(domain)) {
    throw new Error(GENERATE_CSR_ERRORS.DOMAIN_NOT_ASCII);
  }

  // ── Load the private key ─────────────────────────────────────────
  // `createPrivateKey` accepts PEM in PKCS8 form (`-----BEGIN PRIVATE
  // KEY-----`) which is what `generateEd25519Keypair` produces and
  // what `SqliteTlsDomainStore` persists. Any other PEM marker (EC /
  // RSA / encrypted) parses successfully but the `asymmetricKeyType`
  // gate below rejects non-Ed25519 immediately.
  let privateKey: ReturnType<typeof createPrivateKey>;
  try {
    privateKey = createPrivateKey(private_key_pem);
  } catch {
    throw new Error(GENERATE_CSR_ERRORS.KEY_PARSE_FAILED);
  }
  if (privateKey.asymmetricKeyType !== 'ed25519') {
    throw new Error(
      `${GENERATE_CSR_ERRORS.KEY_NOT_ED25519}: got ${privateKey.asymmetricKeyType ?? 'unknown'}`,
    );
  }

  // Export the public half as SPKI DER. The CSR carries this as the
  // `subjectPKInfo` slot directly — Node's SPKI export for Ed25519
  // already wraps the 32-byte raw public key in the RFC 8410 envelope
  // (`SEQUENCE { AlgorithmIdentifier { OID 1.3.101.112 }, BIT STRING
  // raw }`), so no manual SPKI construction is needed.
  let spkiDer: Buffer;
  try {
    const publicKey = createPublicKey(privateKey);
    spkiDer = Buffer.from(
      publicKey.export({ type: 'spki', format: 'der' }),
    );
  } catch {
    throw new Error(GENERATE_CSR_ERRORS.SPKI_EXPORT_FAILED);
  }

  // ── Build CertificationRequestInfo DER ────────────────────────────
  const version = derInteger(0);
  const subject = derSubjectCommonName(domain);
  const attributes = derAttributesWithSan(domain);
  const cri = derSequence(
    Buffer.concat([version, subject, spkiDer, attributes]),
  );

  // ── Sign the CRI ──────────────────────────────────────────────────
  // Ed25519 in Node uses `null` algorithm parameter (per its
  // protocol-baked hash discipline). The signature is exactly 64
  // bytes for Ed25519; it goes into the outer BIT STRING with zero
  // unused bits.
  const signature = nodeSign(null, cri, privateKey);

  // ── Build the outer CertificationRequest ──────────────────────────
  const signatureAlgorithm = derSequence(derOid(ED25519_OID));
  const signatureBits = derBitString(Buffer.from(signature));
  const csr = derSequence(
    Buffer.concat([cri, signatureAlgorithm, signatureBits]),
  );

  // ── PEM-encode ────────────────────────────────────────────────────
  return pemEncode('CERTIFICATE REQUEST', csr);
};

// ────────────────────────────────────────────────────────────────────
// ASN.1 / DER encoding helpers
//
// Tags used:
//   0x02 INTEGER
//   0x03 BIT STRING
//   0x04 OCTET STRING
//   0x06 OBJECT IDENTIFIER
//   0x0c UTF8String
//   0x30 SEQUENCE
//   0x31 SET
//   0x82 [2] IMPLICIT (dNSName in GeneralName)
//   0xa0 [0] EXPLICIT/IMPLICIT (constructed; attributes in CRI)
// ────────────────────────────────────────────────────────────────────

const TAG = {
  INTEGER: 0x02,
  BIT_STRING: 0x03,
  OCTET_STRING: 0x04,
  OID: 0x06,
  UTF8_STRING: 0x0c,
  SEQUENCE: 0x30,
  SET: 0x31,
  /** Constructed context-specific [0] — used IMPLICITly for `attributes`
   *  in `CertificationRequestInfo` (PKCS#10 § 4). */
  CONTEXT_0_CONSTRUCTED: 0xa0,
  /** Primitive context-specific [2] — used IMPLICITly for `dNSName` in
   *  `GeneralName` (RFC 5280 § 4.2.1.6). */
  CONTEXT_2_PRIMITIVE: 0x82,
} as const;

/** DER length encoding. Short form (< 128) is one byte; long form
 *  prefixes a count byte (`0x80 | n`) followed by `n` big-endian
 *  bytes. Throws on negative or absurdly large lengths — DER spec
 *  caps individual TLV at 2^126 bytes but practical CSRs never come
 *  close. */
const derLength = (len: number): Buffer => {
  if (len < 0) {
    throw new Error(`der_length_negative: ${len}`);
  }
  if (len < 128) {
    return Buffer.from([len]);
  }
  const bytes: number[] = [];
  let n = len;
  while (n > 0) {
    bytes.unshift(n & 0xff);
    n = Math.floor(n / 256);
  }
  return Buffer.from([0x80 | bytes.length, ...bytes]);
};

/** Wrap a content buffer in `<tag><length><content>`. */
const derTagged = (tag: number, content: Buffer): Buffer =>
  Buffer.concat([Buffer.from([tag]), derLength(content.length), content]);

const derSequence = (content: Buffer): Buffer =>
  derTagged(TAG.SEQUENCE, content);

const derSet = (content: Buffer): Buffer => derTagged(TAG.SET, content);

/** Encode a non-negative integer. PKCS#10 v1 carries `version = 0` —
 *  the smallest case. The high-bit-set prefix-zero rule preserves the
 *  unsigned semantics DER mandates. */
const derInteger = (n: number): Buffer => {
  if (n < 0) {
    throw new Error(`der_integer_negative: ${n}`);
  }
  if (n === 0) {
    return derTagged(TAG.INTEGER, Buffer.from([0]));
  }
  const bytes: number[] = [];
  let x = n;
  while (x > 0) {
    bytes.unshift(x & 0xff);
    x = Math.floor(x / 256);
  }
  if ((bytes[0] & 0x80) !== 0) {
    bytes.unshift(0);
  }
  return derTagged(TAG.INTEGER, Buffer.from(bytes));
};

const derUtf8String = (s: string): Buffer =>
  derTagged(TAG.UTF8_STRING, Buffer.from(s, 'utf8'));

const derOctetString = (bytes: Buffer): Buffer =>
  derTagged(TAG.OCTET_STRING, bytes);

/** Encode a BIT STRING with zero unused bits. Ed25519 signatures +
 *  raw key bytes are byte-aligned, so unused-bits is always 0 here. */
const derBitString = (bytes: Buffer): Buffer =>
  derTagged(TAG.BIT_STRING, Buffer.concat([Buffer.from([0]), bytes]));

/** Encode an OID from its dotted-decimal form. The first two arcs
 *  pack into one byte (`40 * arc0 + arc1`); remaining arcs use
 *  base-128 with the continuation high-bit set on every byte except
 *  the last. */
const derOid = (oid: string): Buffer => {
  const parts = oid.split('.').map((p) => {
    const n = Number(p);
    if (!Number.isInteger(n) || n < 0) {
      throw new Error(`der_oid_invalid_arc: ${p}`);
    }
    return n;
  });
  if (parts.length < 2) {
    throw new Error(`der_oid_too_short: ${oid}`);
  }
  if (parts[0]! > 2 || (parts[0]! < 2 && parts[1]! >= 40)) {
    throw new Error(`der_oid_invalid_prefix: ${oid}`);
  }
  const bytes: number[] = [parts[0]! * 40 + parts[1]!];
  for (let i = 2; i < parts.length; i++) {
    bytes.push(...base128Encode(parts[i]!));
  }
  return derTagged(TAG.OID, Buffer.from(bytes));
};

/** Base-128 encode with continuation bits. `0` encodes as `[0]`. */
const base128Encode = (n: number): number[] => {
  if (n === 0) return [0];
  const out: number[] = [];
  let x = n;
  while (x > 0) {
    out.unshift(x & 0x7f);
    x = Math.floor(x / 128);
  }
  for (let i = 0; i < out.length - 1; i++) {
    out[i]! |= 0x80;
  }
  return out;
};

/** Build the Subject Name with a single `commonName=<cn>` RDN.
 *
 *      Name ::= SEQUENCE OF RDN
 *      RDN  ::= SET SIZE (1..MAX) OF AttributeTypeAndValue
 *      AttributeTypeAndValue ::= SEQUENCE { type OID, value ANY }
 */
const derSubjectCommonName = (cn: string): Buffer => {
  const attr = derSequence(
    Buffer.concat([derOid(COMMON_NAME_OID), derUtf8String(cn)]),
  );
  const rdn = derSet(attr);
  return derSequence(rdn);
};

/** Build the `[0] IMPLICIT Attributes` slot with an `extensionRequest`
 *  attribute carrying a single SAN extension (`dNSName = <domain>`).
 *
 *      Attribute ::= SEQUENCE {
 *        type   OID,
 *        values SET OF AttributeValue
 *      }
 *      -- extensionRequest:
 *      type   = 1.2.840.113549.1.9.14
 *      values = SET { SEQUENCE OF Extension }
 *
 *      Extension ::= SEQUENCE {
 *        extnID    OID,
 *        critical  BOOLEAN OPTIONAL,
 *        extnValue OCTET STRING
 *      }
 *      -- SAN extension:
 *      extnID    = 2.5.29.17
 *      extnValue = OCTET STRING containing SEQUENCE OF GeneralName
 *
 *      GeneralName ::= CHOICE {
 *        dNSName  [2] IA5String,
 *        ...
 *      }
 *
 *  The SAN extension is NOT marked critical here — most CAs ignore
 *  the critical bit on the extensionRequest path and use the SAN
 *  for the issued cert's SAN. The cloud ACME helper accepts both
 *  shapes per § A.5.3. */
const derAttributesWithSan = (domain: string): Buffer => {
  const dnsName = derTagged(
    TAG.CONTEXT_2_PRIMITIVE,
    Buffer.from(domain, 'ascii'),
  );
  const generalNames = derSequence(dnsName);
  const sanValue = derOctetString(generalNames);
  const sanExtension = derSequence(
    Buffer.concat([derOid(SUBJECT_ALT_NAME_OID), sanValue]),
  );
  const extensions = derSequence(sanExtension);
  const extensionRequest = derSequence(
    Buffer.concat([
      derOid(EXTENSION_REQUEST_OID),
      derSet(extensions),
    ]),
  );
  return derTagged(TAG.CONTEXT_0_CONSTRUCTED, extensionRequest);
};

/** PEM-wrap a DER buffer. RFC 7468 § 3 lines are 64 base64 chars +
 *  trailing newline; the header/footer use the supplied label. */
const pemEncode = (label: string, der: Buffer): string => {
  const b64 = der.toString('base64');
  const lines: string[] = [];
  for (let i = 0; i < b64.length; i += 64) {
    lines.push(b64.slice(i, i + 64));
  }
  return [
    `-----BEGIN ${label}-----`,
    ...lines,
    `-----END ${label}-----`,
    '',
  ].join('\n');
};
