/** Recued canonical design tokens (D-174) — the shared colour system.
 *
 *  `tokens.css` is the source of truth; `THEME_TOKENS_CSS` is its string
 *  form (regenerated by `scripts/generate-tokens-css.mjs`). Surfaces that
 *  SSR or inject styles via JS (the marketplace worker, the webclient /
 *  bridge / dashboard shells) import the string; surfaces that link a
 *  static stylesheet copy `tokens.css` into their build and `<link>` it.
 *  See `tokens.css` for the full rationale + consumption guide. */

export { THEME_TOKENS_CSS } from './tokens.generated.js';
