/** D-145 PA1 — shape of a canonical schema declaration.
 *
 *  Substrate-managed; field types are the closed PA5 form-renderer
 *  type registry (text / textarea / number / boolean / date / timestamp
 *  / enum / ref / array / uuid). PA1 introduces them as data; PA5
 *  consumes them.
 *
 *  Spec: docs/d-145-spec.md § A.3 (form renderer substrate). */

import type { SourceTopTierKind } from '../source-primitive.js';

export type CanonicalFieldType =
  | 'text'
  | 'textarea'
  | 'number'
  | 'boolean'
  | 'date'
  | 'timestamp'
  | 'enum'
  | 'ref'
  | 'array'
  | 'uuid';

/** A single canonical field. The `nullable` flag is the inverse of
 *  required — every field is required unless explicitly nullable. */
export interface CanonicalField {
  name: string;
  type: CanonicalFieldType;
  /** Default false. */
  nullable?: boolean;
  /** Closed list for `type: 'enum'`. */
  enum_values?: readonly string[];
  /** Cardinality discriminator for `type: 'array'`. */
  item_type?: CanonicalFieldType;
  /** Closed list for nested enum-of-ref array items. */
  item_enum_values?: readonly string[];
  /** Inclusive upper bound for `text`. Ignored for other types. */
  max_length?: number;
  /** Regex pattern for `type: 'text'` or `type: 'textarea'`. Surface
   *  format is `RegExp.source` (no flags). PA5 validators run
   *  `new RegExp(pattern)` against the value at validate time. Ignored
   *  for non-text types. § A.3.1 lists this as `text: length, pattern`. */
  pattern?: string;
  /** Inclusive lower bound for `type: 'number'`. § A.3.1 lists this as
   *  `number: min/max/integer`. */
  min?: number;
  /** Inclusive upper bound for `type: 'number'`. */
  max?: number;
  /** When true, `type: 'number'` must be integer. */
  integer?: boolean;
  /** Filled by the storage layer at write — auto-populated; never
   *  user-editable. PA5 form renderer hides these. */
  auto?: boolean;
  /** Default expressed as a literal of the field's resolved
   *  TypeScript shape. `undefined` means no default. */
  default?: unknown;
  /** Free-form description for UI hints + autogenerated docs. */
  description?: string;
}

export type CanonicalRelationshipCardinality = 'one' | 'many';

export interface CanonicalRelationship {
  name: string;
  /** What the relationship points at — e.g. `data.contact`,
   *  `data.task`, `data.calendar.event`. The PA2 resolver maps this
   *  to a typed FK / JSON-array column. */
  ref: string;
  cardinality: CanonicalRelationshipCardinality;
  /** Default false. */
  nullable?: boolean;
  /** Free-form description. */
  description?: string;
}

export type CanonicalIndex = readonly string[];

export interface CanonicalSchema {
  /** § A.2.1 enumerates `task` / `note` / `commitment` / `project` plus
   *  `mail_message` / `calendar.event` / `contact` as Source-able top
   *  tier kinds. PA1 ships canonical schemas for the four work entities;
   *  PA7 widens to `mail_message` (compose-side fields per § A.5.1).
   *  Future schemas (`calendar.event` / `contact`) ride on the same
   *  type. */
  kind: SourceTopTierKind;
  fields: readonly CanonicalField[];
  relationships: readonly CanonicalRelationship[];
  indices: readonly CanonicalIndex[];
}
