/* GENERATED by backend/server/scripts/gen-bundled-pack-reconciliation.mjs — DO NOT EDIT.
 *
 * Embeds the closed D-259 recovery targets because deployed npm/Docker servers
 * do not ship community/. Regenerate: npm run gen:pack-reconciliation. */
/* eslint-disable */
// prettier-ignore
import type { BulkPackManifest } from '@recued/contracts';

// prettier-ignore
export const BUNDLED_PACK_RECONCILIATION_TARGETS: Readonly<Record<string, BulkPackManifest>> =
  {
  "codex-pack": {
    "manifest_version": 2,
    "slug": "codex-pack",
    "publisher": "recued-core",
    "name": "Codex Pack",
    "description": "Use Codex Pack in Recued for developer tools and background. It includes 2 built-in actions. It runs locally on your machine. Actions that change data use Recued's approval controls.",
    "version": 2,
    "recipes": [],
    "requires": [
      "install_bulk_pack"
    ],
    "tags": [
      "pack:codex",
      "codex",
      "cli",
      "developer-tools",
      "background",
      "v3",
      "composition"
    ],
    "pack_kind": "app_pack",
    "service_kind": "cli",
    "contents": [
      {
        "type": "composition",
        "composition": {
          "schema_version": 1,
          "slug": "codex",
          "catalog_kind": "official",
          "ingredients": [
            {
              "slug": "codex",
              "kind": "cli",
              "cli": {
                "tool": "codex",
                "probe": [
                  "codex",
                  "--version"
                ],
                "package_ref": "system_binary:codex",
                "entry_point": "codex"
              }
            }
          ],
          "operations": [
            {
              "op": "codex.status",
              "ingredient": "codex",
              "risk": "read",
              "approval": "never",
              "description": "Return the Codex CLI readiness snapshot.",
              "bind": {
                "kind": "cli_invocation",
                "argv_template": [
                  "codex",
                  "--version"
                ],
                "stdin_handling": "none",
                "shape": "text",
                "exit_code_handling": "zero_is_success"
              },
              "timeout_ms": 15000,
              "cache_ttl_ms": 60000
            },
            {
              "op": "codex.review",
              "ingredient": "codex",
              "risk": "write",
              "approval": "ask",
              "args": [
                {
                  "key": "repo_dir",
                  "affects_target": true
                },
                "task"
              ],
              "description": "Run one Codex repository task as an awaited, owned process tree and return its JSONL event stream. Semantic item-completion events prove progress; owner stop, recipe-budget cancellation, stalls, and wall deadlines terminate the full tree.",
              "bind": {
                "kind": "cli_invocation",
                "argv_template": [
                  "codex",
                  "exec",
                  "--json",
                  "--cd",
                  "{repo_dir}",
                  "{task}"
                ],
                "stdin_handling": "none",
                "shape": "jsonl",
                "exit_code_handling": "zero_is_success",
                "progress": {
                  "contract": "heartbeat",
                  "adapter": "codex-jsonl",
                  "stall_ms": 300000
                }
              },
              "editable_args": [
                {
                  "key": "task",
                  "type": "string",
                  "label": "Task",
                  "required": true
                },
                {
                  "key": "repo_dir",
                  "type": "string",
                  "label": "Repository directory",
                  "required": true,
                  "affects_target": true
                }
              ],
              "timeout_ms": 0,
              "cache_ttl_ms": 0
            }
          ]
        }
      }
    ]
  },
  "yt-dlp": {
    "manifest_version": 2,
    "slug": "yt-dlp",
    "publisher": "recued-core",
    "name": "yt-dlp Pack",
    "description": "Use yt-dlp Pack in Recued for media, video, audio, and download. It includes 4 built-in actions. It runs locally on your machine. Actions that change data use Recued's approval controls.",
    "version": 2,
    "recipes": [],
    "requires": [
      "install_bulk_pack"
    ],
    "tags": [
      "pack:yt-dlp",
      "yt-dlp",
      "cli",
      "media",
      "video",
      "audio",
      "download",
      "metadata",
      "formats",
      "detached",
      "d-179",
      "local-service",
      "v3",
      "composition"
    ],
    "pack_kind": "app_pack",
    "service_kind": "cli",
    "contents": [
      {
        "type": "composition",
        "composition": {
          "schema_version": 1,
          "slug": "yt-dlp",
          "catalog_kind": "official",
          "tags": [
            "yt-dlp",
            "media-download",
            "url-metadata",
            "format-list",
            "detached-cli"
          ],
          "ingredients": [
            {
              "slug": "yt-dlp",
              "kind": "cli",
              "cli": {
                "tool": "yt-dlp",
                "probe": [
                  "yt-dlp",
                  "--version"
                ],
                "package_ref": "system_binary:yt-dlp",
                "entry_point": "yt-dlp"
              }
            }
          ],
          "operations": [
            {
              "op": "ytdlp.version",
              "ingredient": "yt-dlp",
              "risk": "read",
              "approval": "never",
              "description": "Return the local yt-dlp CLI version without loading user configuration.",
              "bind": {
                "kind": "cli_invocation",
                "argv_template": [
                  "yt-dlp",
                  "--ignore-config",
                  "--version"
                ],
                "stdin_handling": "none",
                "shape": "text",
                "exit_code_handling": "zero_is_success"
              },
              "timeout_ms": 15000,
              "cache_ttl_ms": 60000
            },
            {
              "op": "media.metadata",
              "ingredient": "yt-dlp",
              "risk": "read",
              "approval": "ask",
              "args": [
                {
                  "key": "url",
                  "type": "string",
                  "affects_target": true
                }
              ],
              "description": "Fetch extractor metadata for one remote media URL as a single JSON object via yt-dlp --dump-single-json. This is for URL triage before deciding whether to download: title, duration, uploader, webpage URL, thumbnails, available formats, and extractor fields may appear depending on the site. The command runs with --skip-download and does not write media or info-json files. It also ignores local yt-dlp config, cookies, browser cookies, and persistent cache so the result does not silently depend on local account state. Approval is required because metadata extraction contacts the remote site and may reveal the URL being inspected.",
              "bind": {
                "kind": "cli_invocation",
                "argv_template": [
                  "yt-dlp",
                  "--ignore-config",
                  "--no-cache-dir",
                  "--no-cookies",
                  "--no-cookies-from-browser",
                  "--no-playlist",
                  "--skip-download",
                  "--dump-single-json",
                  "--",
                  "{url}"
                ],
                "stdin_handling": "none",
                "shape": "json",
                "exit_code_handling": "zero_is_success"
              },
              "editable_args": [
                {
                  "key": "url",
                  "type": "url",
                  "label": "Source URL",
                  "required": true,
                  "affects_target": true
                }
              ],
              "timeout_ms": 90000,
              "cache_ttl_ms": 0
            },
            {
              "op": "media.formats",
              "ingredient": "yt-dlp",
              "risk": "read",
              "approval": "ask",
              "args": [
                {
                  "key": "url",
                  "type": "string",
                  "affects_target": true
                }
              ],
              "description": "List the available formats for one remote media URL via yt-dlp --list-formats and return the human-readable table. Use this before media.download when a user needs to choose between video, audio, resolution, or container options. The command simulates by default and writes no media output. It ignores local yt-dlp config, cookies, browser cookies, and persistent cache so the result does not silently depend on local account state. Approval is required because format discovery contacts the remote site.",
              "bind": {
                "kind": "cli_invocation",
                "argv_template": [
                  "yt-dlp",
                  "--ignore-config",
                  "--no-cache-dir",
                  "--no-cookies",
                  "--no-cookies-from-browser",
                  "--no-playlist",
                  "--list-formats",
                  "--",
                  "{url}"
                ],
                "stdin_handling": "none",
                "shape": "text",
                "exit_code_handling": "zero_is_success"
              },
              "editable_args": [
                {
                  "key": "url",
                  "type": "url",
                  "label": "Source URL",
                  "required": true,
                  "affects_target": true
                }
              ],
              "timeout_ms": 90000,
              "cache_ttl_ms": 0
            },
            {
              "op": "media.download",
              "ingredient": "yt-dlp",
              "risk": "write",
              "approval": "ask",
              "args": [
                {
                  "key": "url",
                  "affects_target": true
                },
                "format"
              ],
              "description": "Download one video or audio stream as an awaited, owned process tree and return the completed artifact as an opaque data.file reference. Monotonically increasing yt-dlp percentages prove progress; owner stop, recipe-budget cancellation, stalls, and wall deadlines terminate the full tree. The command ignores local config, cookies, browser cookies, playlists, and persistent cache.",
              "bind": {
                "kind": "cli_invocation",
                "argv_template": [
                  "yt-dlp",
                  "--ignore-config",
                  "--no-cache-dir",
                  "--no-cookies",
                  "--no-cookies-from-browser",
                  "--no-playlist",
                  "--newline",
                  "--format",
                  "{format}",
                  "-o",
                  "{out_dir}/media.%(ext)s",
                  "--",
                  "{url}"
                ],
                "stdin_handling": "none",
                "shape": "ref",
                "storage": "cas",
                "exit_code_handling": "zero_is_success",
                "progress": {
                  "contract": "heartbeat",
                  "adapter": "yt-dlp-progress",
                  "stall_ms": 90000
                },
                "output_capture": {
                  "dir_arg": "out_dir",
                  "mime_type": "application/octet-stream"
                }
              },
              "editable_args": [
                {
                  "key": "url",
                  "type": "url",
                  "label": "Source URL",
                  "required": true,
                  "affects_target": true
                },
                {
                  "key": "format",
                  "type": "enum",
                  "label": "Format",
                  "required": false,
                  "values": [
                    "best",
                    "bestvideo+bestaudio",
                    "bestaudio",
                    "worst"
                  ],
                  "default": "best"
                }
              ],
              "timeout_ms": 0,
              "cache_ttl_ms": 0
            }
          ]
        }
      }
    ]
  },
  "cloudflared": {
    "manifest_version": 2,
    "slug": "cloudflared",
    "publisher": "recued-core",
    "name": "Cloudflared Pack",
    "description": "Use Cloudflared Pack in Recued for tunnel, webhook, and background. It includes 1 built-in action. It runs locally on your machine. Actions that change data use Recued's approval controls.",
    "version": 2,
    "recipes": [],
    "requires": [
      "install_bulk_pack"
    ],
    "tags": [
      "pack:cloudflared",
      "cloudflared",
      "cloudflare",
      "tunnel",
      "webhook",
      "cli",
      "background",
      "d-179",
      "composition"
    ],
    "pack_kind": "app_pack",
    "service_kind": "cli",
    "contents": [
      {
        "type": "composition",
        "composition": {
          "schema_version": 1,
          "slug": "cloudflared",
          "catalog_kind": "official",
          "ingredients": [
            {
              "slug": "cloudflared",
              "kind": "cli",
              "cli": {
                "tool": "cloudflared",
                "probe": [
                  "cloudflared",
                  "--version"
                ],
                "package_ref": "system_binary:cloudflared",
                "entry_point": "cloudflared"
              }
            }
          ],
          "operations": [
            {
              "op": "tunnel.run_detached",
              "ingredient": "cloudflared",
              "risk": "admin",
              "approval": "ask",
              "args": [
                {
                  "key": "tunnel_name",
                  "affects_target": true
                },
                {
                  "key": "result_dir",
                  "affects_target": true
                },
                {
                  "key": "key",
                  "affects_target": true
                }
              ],
              "description": "Start `cloudflared tunnel run <tunnel_name>` as a Recued-supervised service. The operation binds this connector's local metrics server to 127.0.0.1:20241 and returns only after its `/ready` endpoint confirms an active Cloudflare edge connection. It retains the compatible launch receipt and remains owned by the supervisor for health checks, process-group stop, crash restart, and server-start recovery.",
              "bind": {
                "kind": "cli_invocation",
                "argv_template": [
                  "cloudflared",
                  "tunnel",
                  "--metrics",
                  "127.0.0.1:20241",
                  "run",
                  "{tunnel_name}"
                ],
                "stdin_handling": "none",
                "shape": "text",
                "exit_code_handling": "zero_is_success",
                "detached": {
                  "mode": "runtime_managed",
                  "completion": {
                    "kind": "marker_file",
                    "exit_pattern": "{result_dir}/{key}.exit.{code}",
                    "log_pattern": "{result_dir}/{key}.log"
                  },
                  "cancel": {
                    "kind": "process_group",
                    "pid_pattern": "{result_dir}/{key}.pid"
                  },
                  "supervision": {
                    "restart_policy": "on-crash",
                    "restart_on_server_start": true,
                    "readiness": {
                      "kind": "http_ok",
                      "url": "http://127.0.0.1:20241/ready",
                      "status_ok": [
                        200
                      ],
                      "timeout_ms": 5000
                    },
                    "health": {
                      "kind": "http_ok",
                      "url": "http://127.0.0.1:20241/ready",
                      "status_ok": [
                        200
                      ],
                      "timeout_ms": 5000
                    },
                    "ready_timeout_ms": 30000
                  }
                }
              },
              "editable_args": [
                {
                  "key": "tunnel_name",
                  "type": "string",
                  "label": "Tunnel name",
                  "required": true,
                  "affects_target": true
                },
                {
                  "key": "result_dir",
                  "type": "string",
                  "label": "Result directory",
                  "required": true,
                  "affects_target": true
                },
                {
                  "key": "key",
                  "type": "string",
                  "label": "Result marker key",
                  "required": true,
                  "affects_target": true,
                  "validation": {
                    "pattern": "^[A-Za-z0-9_-]+$"
                  }
                }
              ],
              "timeout_ms": 15000,
              "cache_ttl_ms": 0
            }
          ]
        }
      }
    ]
  },
  "ollama": {
    "manifest_version": 2,
    "slug": "ollama",
    "publisher": "recued-core",
    "name": "Ollama Pack",
    "description": "Use Ollama Pack in Recued for AI, local, inference, and summary. It includes 3 built-in actions. It runs locally on your machine. Actions that change data use Recued's approval controls.",
    "version": 2,
    "recipes": [],
    "requires": [
      "install_bulk_pack"
    ],
    "tags": [
      "pack:ollama",
      "ollama",
      "cli",
      "ai",
      "local",
      "inference",
      "summary",
      "privacy",
      "no-egress",
      "deterministic",
      "local-service",
      "v3",
      "composition"
    ],
    "pack_kind": "app_pack",
    "service_kind": "cli",
    "contents": [
      {
        "type": "composition",
        "composition": {
          "schema_version": 1,
          "slug": "ollama",
          "catalog_kind": "official",
          "ingredients": [
            {
              "slug": "ollama",
              "kind": "cli",
              "cli": {
                "tool": "ollama",
                "probe": [
                  "ollama",
                  "--version"
                ],
                "package_ref": "system_binary:ollama",
                "entry_point": "ollama"
              }
            }
          ],
          "operations": [
            {
              "op": "model.run",
              "ingredient": "ollama",
              "risk": "read",
              "approval": "never",
              "args": [
                "model",
                "prompt"
              ],
              "description": "Run a prompt against a locally-installed Ollama model via the local ollama CLI (ollama run <model> <prompt>) and return the model's reply as captured text in the op result's `stdout` field. A local, no-egress inference: the prompt never leaves the paired recued-server, and the reply is a transient text value the next step consumes directly (no durable write, no file). The target model must already be pulled (ollama pull <model>) — a missing model fails the run rather than triggering a mid-recipe network download. The prompt is passed as a single discrete argv element (shell:false), so it cannot inject ollama flags. Read-tier because the op mutates nothing and sends nothing; the cost is local compute. For structured-JSON contracts use the ai-* functions instead — this op is the escape hatch for keeping private content on the machine.",
              "bind": {
                "kind": "cli_invocation",
                "argv_template": [
                  "ollama",
                  "run",
                  "{model}",
                  "{prompt}"
                ],
                "stdin_handling": "none",
                "shape": "text",
                "exit_code_handling": "zero_is_success"
              },
              "editable_args": [
                {
                  "key": "model",
                  "type": "string",
                  "label": "Model",
                  "required": true
                },
                {
                  "key": "prompt",
                  "type": "string",
                  "label": "Prompt",
                  "required": true
                }
              ],
              "timeout_ms": 90000,
              "cache_ttl_ms": 0
            },
            {
              "op": "model.list",
              "ingredient": "ollama",
              "risk": "read",
              "approval": "never",
              "description": "List the models pulled into the local Ollama install via the local ollama CLI (ollama list) — the captured table is returned in the op result's `stdout` (a string the next step parses). Read-tier + approval=never: it inspects local state and mutates nothing, sends nothing. Pulling a new model stays a manual setup step (ollama pull <model>) — the model.run op assumes the target model is already present. Requires the ollama binary on PATH.",
              "bind": {
                "kind": "cli_invocation",
                "argv_template": [
                  "ollama",
                  "list"
                ],
                "stdin_handling": "none",
                "shape": "text",
                "exit_code_handling": "zero_is_success"
              },
              "timeout_ms": 15000,
              "cache_ttl_ms": 0
            },
            {
              "op": "serve.run_detached",
              "ingredient": "ollama",
              "risk": "admin",
              "approval": "ask",
              "args": [
                {
                  "key": "result_dir",
                  "affects_target": true
                },
                {
                  "key": "key",
                  "affects_target": true
                }
              ],
              "description": "Start the local Ollama inference daemon as a Recued-supervised service. The operation returns only after the local API answers, retains the compatible launch receipt, and remains owned by the supervisor for HTTP health checks, process-group stop, crash restart, and server-start recovery. admin-risk + approval=ask because it opens a long-running local listener.",
              "bind": {
                "kind": "cli_invocation",
                "argv_template": [
                  "ollama",
                  "serve"
                ],
                "stdin_handling": "none",
                "shape": "text",
                "exit_code_handling": "zero_is_success",
                "detached": {
                  "mode": "runtime_managed",
                  "completion": {
                    "kind": "marker_file",
                    "exit_pattern": "{result_dir}/{key}.exit.{code}",
                    "log_pattern": "{result_dir}/{key}.log"
                  },
                  "cancel": {
                    "kind": "process_group",
                    "pid_pattern": "{result_dir}/{key}.pid"
                  },
                  "supervision": {
                    "restart_policy": "on-crash",
                    "restart_on_server_start": true,
                    "readiness": {
                      "kind": "http_ok",
                      "url": "http://127.0.0.1:11434/api/tags",
                      "status_ok": [
                        200
                      ],
                      "timeout_ms": 3000
                    },
                    "health": {
                      "kind": "http_ok",
                      "url": "http://127.0.0.1:11434/api/tags",
                      "status_ok": [
                        200
                      ],
                      "timeout_ms": 3000
                    },
                    "ready_timeout_ms": 30000
                  }
                }
              },
              "editable_args": [
                {
                  "key": "result_dir",
                  "type": "string",
                  "label": "Result directory",
                  "required": true,
                  "affects_target": true
                },
                {
                  "key": "key",
                  "type": "string",
                  "label": "Result marker key",
                  "required": true,
                  "affects_target": true,
                  "validation": {
                    "pattern": "^[A-Za-z0-9_-]+$"
                  }
                }
              ],
              "timeout_ms": 15000,
              "cache_ttl_ms": 0
            }
          ]
        }
      }
    ]
  }
} as unknown as Readonly<Record<string, BulkPackManifest>>;
