/* GENERATED by backend/server/scripts/gen-bundled-foundation.mjs — DO NOT EDIT.
 *
 * Embeds pre_install (foundation) pack manifests + their recipes so a deployed
 * server pre-installs Day-1 content even though the distribution ships no
 * community/ dir. Regenerate: node backend/server/scripts/gen-bundled-foundation.mjs
 * (bundled-foundation-embed.test.ts fails if this drifts from community/). */
/* eslint-disable */
// prettier-ignore
import type { BulkPackManifest, RecipeDefinition } from '@recued/contracts';

// prettier-ignore
export const BUNDLED_FOUNDATION_PACKS: readonly BulkPackManifest[] =
  [
  {
    "manifest_version": 1,
    "slug": "personal-organizer-foundation",
    "publisher": "recued-core",
    "name": "Personal Organizer Foundation",
    "description": "Day-1 personal-organizer pack per D-145 § A.6. Pre-installs on first server init and composes built-in work entities (`task` / `note` / `commitment` / `project`) with PA9 enrichment producers (`open_loop_pressure` / `project_stall_signal` / `project_next_action_gap` / `commitment_reliability_band` / `note_relevance_decay`) into ten recipes: 4 Layer-2 visible views (today / open-commitments / stalled-projects / recent-notes-by-topic), 2 Layer-1 silent producers reactive on inbound mail (extract-commitments-from-mail / extract-tasks-from-mail), 1 Layer-2 visible alert reactive on inbound mail (triage-inbox), D-193 reminders (chat capture plus hidden due notifier), and the schedule-recipe control for installed recipes. Ships three canonical Standing Instructions as conservative safety defaults: an approval gate on composing email to contacts the substrate has only ever seen mentioned (never sent / received-from); a `min_tier: mid` floor for `schedule_meeting` so timezone-sensitive proposals don't ride the cheapest tier; and a `ban_omission_class: permission_scope` clause for `recipe_invoke` so foundation-pack views surface permission gaps instead of silently truncating. The substrate is provided by D-145 PA1-PA9 + the existing kernel ingredients; this pack is the consumer that turns the substrate into Day-1 value.",
    "version": 4,
    "pre_install": true,
    "recipes": [
      {
        "slug": "today",
        "version": 1
      },
      {
        "slug": "open-commitments",
        "version": 1
      },
      {
        "slug": "stalled-projects",
        "version": 1
      },
      {
        "slug": "recent-notes-by-topic",
        "version": 1
      },
      {
        "slug": "extract-commitments-from-mail",
        "version": 1
      },
      {
        "slug": "extract-tasks-from-mail",
        "version": 1
      },
      {
        "slug": "triage-inbox",
        "version": 1
      },
      {
        "slug": "remind-me-of",
        "version": 1
      },
      {
        "slug": "reminder-due-notifier",
        "version": 1
      },
      {
        "slug": "schedule-recipe",
        "version": 1
      }
    ],
    "requires": [
      "install_bulk_pack",
      "notification_send"
    ],
    "tags": [
      "pack:personal-organizer",
      "foundation",
      "d-145",
      "tasks",
      "commitments",
      "projects",
      "notes",
      "calendar",
      "mail"
    ],
    "service_kind": "workflow"
  },
  {
    "manifest_version": 2,
    "slug": "reception-approval",
    "publisher": "recued-core",
    "name": "Reception — Approval",
    "description": "Review-by-default approval reception. An incoming scoped approval (approve / confirm / pick a time / answer) lands a pending record; a review-then-approve workflow holds the materialize operation at the Gateway gate, where you approve (editing the resulting commitment first) or reject. Materializes a commitment to your local warehouse by default — no external connection required.",
    "version": 1,
    "pre_install": true,
    "recipes": [],
    "requires": [
      "install_bulk_pack"
    ],
    "tags": [
      "pack:reception",
      "reception",
      "reception-approval",
      "l2"
    ],
    "pack_kind": "app_pack",
    "contents": [
      {
        "type": "composition",
        "composition": {
          "schema_version": 1,
          "slug": "reception-approval",
          "catalog_kind": "private_byo",
          "ingredients": [
            {
              "slug": "reception-approval",
              "kind": "http",
              "http": {
                "base": "https://reception.local",
                "connection": "reception-approval"
              },
              "entities": {
                "approval": {
                  "fields": [
                    {
                      "field_path": "id",
                      "type": "string",
                      "maps_to": "id",
                      "description": "Materialized commitment id."
                    },
                    {
                      "field_path": "statement",
                      "type": "string",
                      "maps_to": "statement",
                      "description": "Commitment statement."
                    }
                  ]
                }
              }
            }
          ],
          "operations": [
            {
              "op": "approval.materialize",
              "ingredient": "reception-approval",
              "risk": "write",
              "approval": "ask",
              "out": "result",
              "args": [
                "title",
                "body",
                "promised_for_at",
                {
                  "key": "source_id",
                  "affects_target": true
                }
              ],
              "description": "Materialize a consumed approval into an inbound commitment in the local warehouse (the review-then-approve projection). Approval-required: the Gateway gate holds it pending so the user reviews + edits before it runs. The `https://reception.local` base url (surfaces_seed) is a LOCAL-DISPATCH sentinel, not a reachable endpoint — on approve-resume the ingredient executor routes this op to the in-process `reception-materialize` kernel ingredient (runReceptionProjection), so the materialize never makes an HTTP call (D-173 I-2 / P1-dispatch).",
              "bind": {
                "kind": "rest",
                "method": "POST",
                "path_template": "/reception/approval/materialize"
              },
              "request_schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "body": {
                    "type": "string"
                  },
                  "promised_for_at": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "source_id": {
                    "type": "string"
                  }
                },
                "required": [
                  "title"
                ]
              },
              "editable_args": [
                {
                  "key": "title",
                  "type": "string",
                  "label": "Summary",
                  "required": true
                },
                {
                  "key": "body",
                  "type": "string",
                  "label": "Commitment statement"
                },
                {
                  "key": "promised_for_at",
                  "type": "datetime",
                  "label": "Due"
                },
                {
                  "key": "source_id",
                  "type": "string",
                  "label": "Destination",
                  "options_source": "reception_destination_sources",
                  "affects_target": true
                }
              ]
            }
          ],
          "default_grants": [
            "reception-approval.approval.write"
          ],
          "recipe_templates": [
            {
              "template": "review-then-approve",
              "trigger": {
                "entity": "reception_approval_intent",
                "field": "processing_outcome",
                "value": "pending"
              },
              "operation": "approval.materialize"
            }
          ]
        }
      }
    ]
  },
  {
    "manifest_version": 2,
    "slug": "reception-drop",
    "publisher": "recued-core",
    "name": "Reception — Drop",
    "description": "Review-by-default file-drop reception. A visitor uploads a file and it lands a pending record; a review-then-approve workflow holds the materialize operation at the Gateway gate, where you approve (editing the title / details / destination first) or reject. On approve it materializes a task in your local warehouse with the uploaded file attached (data.link role:'attachment', D-172) — no external connection required. Every upload is reviewed — there is no way to skip the gate.",
    "version": 1,
    "pre_install": true,
    "recipes": [],
    "requires": [
      "install_bulk_pack"
    ],
    "tags": [
      "pack:reception",
      "reception",
      "reception-drop",
      "l2"
    ],
    "pack_kind": "app_pack",
    "contents": [
      {
        "type": "composition",
        "composition": {
          "schema_version": 1,
          "slug": "reception-drop",
          "catalog_kind": "private_byo",
          "ingredients": [
            {
              "slug": "reception-drop",
              "kind": "http",
              "http": {
                "base": "https://reception.local",
                "connection": "reception-drop"
              },
              "entities": {
                "drop": {
                  "fields": [
                    {
                      "field_path": "id",
                      "type": "string",
                      "maps_to": "id",
                      "description": "Materialized task id."
                    },
                    {
                      "field_path": "title",
                      "type": "string",
                      "maps_to": "title",
                      "description": "Drop task title (the uploaded filename)."
                    },
                    {
                      "field_path": "body",
                      "type": "string",
                      "maps_to": "body",
                      "optional": true,
                      "description": "Visitor's description."
                    }
                  ]
                }
              }
            }
          ],
          "operations": [
            {
              "op": "drop.materialize",
              "ingredient": "reception-drop",
              "risk": "write",
              "approval": "ask",
              "out": "result",
              "args": [
                "title",
                "body",
                {
                  "key": "source_id",
                  "affects_target": true
                }
              ],
              "description": "Materialize a reviewed file-drop into a task in the local warehouse with the uploaded file attached (the review-then-approve projection — the file was ingested into data.file.received at submit; on approve the task is written and the file is linked via data.link role:'attachment', D-172). Approval-required: the Gateway gate holds it pending so the user reviews + edits the title / details before it runs. The `https://reception.local` base url (surfaces_seed) is a LOCAL-DISPATCH sentinel, not a reachable endpoint — on approve-resume the ingredient executor routes this op to the in-process `reception-materialize` kernel ingredient (runReceptionProjection), so the materialize never makes an HTTP call (D-173 I-2 / P1-dispatch).",
              "bind": {
                "kind": "rest",
                "method": "POST",
                "path_template": "/reception/drop/materialize"
              },
              "request_schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "body": {
                    "type": "string"
                  },
                  "source_id": {
                    "type": "string"
                  }
                },
                "required": [
                  "title"
                ]
              },
              "editable_args": [
                {
                  "key": "title",
                  "type": "string",
                  "label": "Title",
                  "required": true
                },
                {
                  "key": "body",
                  "type": "string",
                  "label": "Details"
                },
                {
                  "key": "source_id",
                  "type": "string",
                  "label": "Destination",
                  "options_source": "reception_destination_sources",
                  "affects_target": true
                }
              ]
            }
          ],
          "default_grants": [
            "reception-drop.drop.write"
          ],
          "recipe_templates": [
            {
              "template": "review-then-approve",
              "trigger": {
                "entity": "reception_drop_blob_metadata",
                "field": "processing_outcome",
                "value": "pending"
              },
              "operation": "drop.materialize"
            }
          ]
        }
      }
    ]
  },
  {
    "manifest_version": 2,
    "slug": "reception-intake",
    "publisher": "recued-core",
    "name": "Reception — Intake",
    "description": "Review-by-default intake reception. An incoming form submission lands in Reception Inbox; approval always retains the canonical response in Data. Store-only forms finish there, while forms with an entity target also materialize a task, note, or commitment — no external connection required.",
    "version": 1,
    "pre_install": true,
    "recipes": [],
    "requires": [
      "install_bulk_pack"
    ],
    "tags": [
      "pack:reception",
      "reception",
      "reception-intake",
      "l2"
    ],
    "pack_kind": "app_pack",
    "contents": [
      {
        "type": "composition",
        "composition": {
          "schema_version": 1,
          "slug": "reception-intake",
          "catalog_kind": "private_byo",
          "ingredients": [
            {
              "slug": "reception-intake",
              "kind": "http",
              "http": {
                "base": "https://reception.local",
                "connection": "reception-intake"
              },
              "entities": {
                "intake": {
                  "fields": [
                    {
                      "field_path": "id",
                      "type": "string",
                      "maps_to": "id",
                      "description": "Deterministic completion id: the canonical submission id for form_response, or the materialized entity id for an entity target."
                    },
                    {
                      "field_path": "title",
                      "type": "string",
                      "maps_to": "title",
                      "description": "Submission title."
                    },
                    {
                      "field_path": "body",
                      "type": "string",
                      "maps_to": "body",
                      "optional": true,
                      "description": "Submission details."
                    }
                  ]
                }
              }
            }
          ],
          "operations": [
            {
              "op": "intake.materialize",
              "ingredient": "reception-intake",
              "risk": "write",
              "approval": "ask",
              "out": "result",
              "args": [
                "title",
                "body",
                {
                  "key": "source_id",
                  "affects_target": true
                }
              ],
              "description": "Complete a reviewed intake submission through the local review projection. Approval-required: the Gateway gate holds it pending first. A `form_response` target verifies the canonical accepted response and creates no second entity; task, note, and commitment targets materialize into the local warehouse. The `https://reception.local` base url is a LOCAL-DISPATCH sentinel, never a reachable endpoint.",
              "bind": {
                "kind": "rest",
                "method": "POST",
                "path_template": "/reception/intake/materialize"
              },
              "request_schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "body": {
                    "type": "string"
                  },
                  "source_id": {
                    "type": "string"
                  }
                },
                "required": [
                  "title"
                ]
              },
              "editable_args": [
                {
                  "key": "title",
                  "type": "string",
                  "label": "Title",
                  "required": true
                },
                {
                  "key": "body",
                  "type": "string",
                  "label": "Details"
                },
                {
                  "key": "source_id",
                  "type": "string",
                  "label": "Destination",
                  "options_source": "reception_destination_sources",
                  "affects_target": true
                }
              ]
            }
          ],
          "default_grants": [
            "reception-intake.intake.write"
          ],
          "recipe_templates": [
            {
              "template": "review-then-approve",
              "trigger": {
                "entity": "reception_form_submission",
                "field": "processing_outcome",
                "value": "pending"
              },
              "operation": "intake.materialize"
            }
          ]
        }
      }
    ]
  },
  {
    "manifest_version": 2,
    "slug": "reception-scheduling",
    "publisher": "recued-core",
    "name": "Reception — Scheduling",
    "description": "Review-by-default scheduling reception (a booking front-door). A visitor picks a slot and the booking lands a pending record; a review-then-approve workflow holds the materialize operation at the Gateway gate, where you approve (editing the slot time / details first) or reject. Materializes a booking in your local warehouse — a mutable business record that owns its own slot and lifecycle (confirmed / completed / no_show / cancelled). A booking is never written to your calendar: the calendar is personal, a booking is business (D-210 A.2). Scheduling never auto-books (D-173 I-7).",
    "version": 4,
    "pre_install": true,
    "recipes": [
      {
        "slug": "reschedule-calendar-event",
        "version": 1
      },
      {
        "slug": "reschedule-booking",
        "version": 1
      },
      {
        "slug": "reschedule-booking-managed",
        "version": 1
      }
    ],
    "requires": [
      "install_bulk_pack"
    ],
    "tags": [
      "pack:reception",
      "reception",
      "reception-scheduling",
      "l2"
    ],
    "pack_kind": "app_pack",
    "contents": [
      {
        "type": "composition",
        "composition": {
          "schema_version": 1,
          "slug": "reception-scheduling",
          "catalog_kind": "private_byo",
          "ingredients": [
            {
              "slug": "reception-scheduling",
              "kind": "http",
              "http": {
                "base": "https://reception.local",
                "connection": "reception-scheduling"
              },
              "entities": {
                "scheduling": {
                  "fields": [
                    {
                      "field_path": "id",
                      "type": "string",
                      "maps_to": "id",
                      "description": "Materialized booking id."
                    },
                    {
                      "field_path": "summary",
                      "type": "string",
                      "maps_to": "summary",
                      "description": "Owner-facing booking title."
                    }
                  ]
                }
              }
            }
          ],
          "operations": [
            {
              "op": "scheduling.materialize",
              "ingredient": "reception-scheduling",
              "risk": "write",
              "approval": "ask",
              "out": "result",
              "args": [
                "title",
                "body",
                "start_at",
                "notify_visitor"
              ],
              "description": "Materialize a reviewed reservation into a BOOKING row (the review-then-approve projection). ⛔ It does NOT create a calendar event and never has since D-210 A.2: booking ⟂ calendar, so the booking carries its own slot_start_at / slot_end_at and is the only artifact. Approval-required: the Gateway gate holds it pending so the owner reviews + edits the slot start / details before it runs, and the EDITED value is what is minted — the reservation row keeps what the visitor originally ASKED, this records what was AGREED. A past-slot booking is never materialized (I-7) — the projection refuses once the slot is in the past. Set notify_visitor to tell the visitor their booking is confirmed; it is off unless the owner turns it on for this approval, and it needs a send-capable sender configured on the scheduling link. The `https://reception.local` base url (surfaces_seed) is a LOCAL-DISPATCH sentinel, not a reachable endpoint — on approve-resume the ingredient executor routes this op to the in-process `reception-materialize` kernel ingredient (runReceptionProjection), so the materialize never makes an HTTP call (D-173 I-2 / P1-dispatch).",
              "bind": {
                "kind": "rest",
                "method": "POST",
                "path_template": "/reception/scheduling/materialize"
              },
              "request_schema": {
                "type": "object",
                "properties": {
                  "title": {
                    "type": "string"
                  },
                  "body": {
                    "type": "string"
                  },
                  "start_at": {
                    "type": "number"
                  },
                  "notify_visitor": {
                    "type": "boolean"
                  }
                },
                "required": [
                  "title"
                ]
              },
              "editable_args": [
                {
                  "key": "title",
                  "type": "string",
                  "label": "Summary",
                  "required": true
                },
                {
                  "key": "body",
                  "type": "string",
                  "label": "Details"
                },
                {
                  "key": "start_at",
                  "type": "datetime",
                  "label": "Slot start"
                },
                {
                  "key": "notify_visitor",
                  "type": "boolean",
                  "label": "Tell the visitor their booking is confirmed"
                }
              ]
            }
          ],
          "default_grants": [
            "reception-scheduling.scheduling.write"
          ],
          "recipe_templates": [
            {
              "template": "review-then-approve",
              "trigger": {
                "entity": "reception_form_submission",
                "field": "processing_outcome",
                "value": "pending"
              },
              "operation": "scheduling.materialize"
            }
          ]
        }
      }
    ]
  }
] as unknown as readonly BulkPackManifest[];

// prettier-ignore
export const BUNDLED_FOUNDATION_RECIPES: Readonly<Record<string, RecipeDefinition>> =
  {
  "extract-commitments-from-mail": {
    "recipe_id": "extract-commitments-from-mail",
    "chat_exposed": true,
    "version": 1,
    "ttl": 60,
    "metadata": {
      "name": "Extract commitments from mail (D-145 PA10)",
      "description": "Extract commitments from an inbound email into Recued's commitment tracker — who promised what to whom, with optional deadline and monetary amount. Thread-aware: a reply like 'yes, please send that by Friday' binds to the prior message, not the reply. Fires automatically on each inbound message; records only extractions above the confidence floor (default 0.7), resolves the counterparty to a known contact when possible, and the extractor model sees only PII-aliased text, never the raw sender.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "email",
        "mail",
        "commitment",
        "work-entity",
        "reactive",
        "silent-producer",
        "pack:personal-organizer",
        "ai_surface"
      ],
      "budget_ms": 30000
    },
    "variables": {
      "confidence_threshold": {
        "label": "Minimum extraction confidence (0..1) to create a commitment row",
        "type": "number",
        "default": 0.7
      }
    },
    "requires": [],
    "event_triggers": [
      {
        "event": "data.mail.**.created"
      }
    ],
    "prefetch_steps": [
      {
        "id": "message",
        "op": "core.mail.get",
        "args": {
          "slug": "{{context.event.payload.slug}}",
          "record_id": "{{context.event.payload.record_id}}"
        }
      }
    ],
    "steps": [
      {
        "id": "subject",
        "transform": "default",
        "value": "{{step.message.record.hot_fields.subject}}",
        "fallback": ""
      },
      {
        "id": "from_email",
        "transform": "default",
        "value": "{{step.message.record.hot_fields.from}}",
        "fallback": ""
      },
      {
        "id": "thread_id",
        "transform": "default",
        "value": "{{step.message.record.hot_fields.thread_id}}",
        "fallback": ""
      },
      {
        "id": "has_thread_id",
        "transform": "compare",
        "left": "{{step.thread_id}}",
        "operator": "is_not_empty"
      },
      {
        "id": "thread",
        "skip_when": "{{step.has_thread_id}} not_equal true",
        "op": "core.mail.thread-read",
        "args": {
          "slug": "{{context.event.payload.slug}}",
          "thread_id": "{{step.thread_id}}",
          "max_messages": 5
        }
      },
      {
        "id": "thread_messages",
        "transform": "default",
        "value": "{{step.thread.messages}}",
        "fallback": []
      },
      {
        "id": "thread_body_reads",
        "op": "core.mail.body-read",
        "foreach": "{{step.thread_messages}}",
        "args": {
          "slug": "{{context.event.payload.slug}}",
          "record_id": "{{item.record_id}}",
          "max_chars": 32000
        }
      },
      {
        "id": "thread_messages_with_body",
        "transform": "filter",
        "array": "{{step.thread_body_reads}}",
        "field": "result.body",
        "operator": "is_not_empty"
      },
      {
        "id": "thread_body_segments",
        "transform": "pluck",
        "array": "{{step.thread_messages_with_body}}",
        "field": "result.body"
      },
      {
        "id": "thread_body",
        "transform": "join",
        "array": "{{step.thread_body_segments}}",
        "separator": "\n\n---\n\n"
      },
      {
        "id": "single_body_read",
        "skip_when": "{{step.has_thread_id}} equal true",
        "op": "core.mail.body-read",
        "args": {
          "slug": "{{context.event.payload.slug}}",
          "record_id": "{{context.event.payload.record_id}}",
          "max_chars": 32000
        }
      },
      {
        "id": "single_body",
        "transform": "default",
        "value": "{{step.single_body_read.body}}",
        "fallback": ""
      },
      {
        "id": "body",
        "transform": "ternary",
        "if": "{{step.has_thread_id}}",
        "then": "{{step.thread_body}}",
        "else": "{{step.single_body}}"
      },
      {
        "id": "body_present",
        "transform": "compare",
        "left": "{{step.body}}",
        "operator": "is_not_empty"
      },
      {
        "id": "skip_empty",
        "transform": "compare",
        "left": "{{step.body_present}}",
        "operator": "not_equal",
        "right": true
      },
      {
        "id": "protect",
        "transform": "pii-protect",
        "data": {
          "from": "{{step.from_email}}",
          "subject": "{{step.subject}}",
          "body": "{{step.body}}"
        },
        "fields": [
          {
            "path": "from",
            "kind": "email"
          },
          {
            "path": "subject",
            "kind": "content"
          },
          {
            "path": "body",
            "kind": "content"
          }
        ]
      },
      {
        "id": "extract",
        "skip_when": "{{step.skip_empty}} equal true",
        "op": "core.ai.extract",
        "args": {
          "llm.data": "Subject: {{step.protect.aliased.subject}}\n\n{{step.protect.aliased.body}}",
          "llm.fields": [
            "statement",
            "direction",
            "promised_for_at_iso",
            "counterparty_email",
            "monetary_amount",
            "monetary_currency",
            "derivation_confidence"
          ],
          "llm.model_hint": "fast"
        }
      },
      {
        "id": "restore",
        "transform": "pii-restore",
        "data": "{{step.extract}}",
        "ledger_handle": "{{step.protect.ledger_handle}}"
      },
      {
        "id": "extracted_statement",
        "transform": "default",
        "value": "{{step.restore.restored.statement}}",
        "fallback": ""
      },
      {
        "id": "extracted_direction",
        "transform": "default",
        "value": "{{step.restore.restored.direction}}",
        "fallback": "inbound"
      },
      {
        "id": "extracted_confidence",
        "transform": "default",
        "value": "{{step.restore.restored.derivation_confidence}}",
        "fallback": 0
      },
      {
        "id": "extracted_counterparty_email",
        "transform": "default",
        "value": "{{step.restore.restored.counterparty_email}}",
        "fallback": ""
      },
      {
        "id": "counterparty_email",
        "transform": "trim",
        "input": "{{step.extracted_counterparty_email}}"
      },
      {
        "id": "extracted_monetary_amount",
        "transform": "default",
        "value": "{{step.restore.restored.monetary_amount}}",
        "fallback": ""
      },
      {
        "id": "extracted_monetary_currency",
        "transform": "default",
        "value": "{{step.restore.restored.monetary_currency}}",
        "fallback": ""
      },
      {
        "id": "promised_for_at",
        "transform": "date_parse",
        "input": "{{step.restore.restored.promised_for_at_iso}}"
      },
      {
        "id": "has_monetary",
        "transform": "all",
        "conditions": [
          "{{step.extracted_monetary_amount}} is_not_empty",
          "{{step.extracted_monetary_currency}} is_not_empty"
        ]
      },
      {
        "id": "monetary_value",
        "skip_when": "{{step.has_monetary}} not_equal true",
        "transform": "merge",
        "sources": [
          {
            "amount": "{{step.extracted_monetary_amount}}",
            "currency": "{{step.extracted_monetary_currency}}"
          }
        ]
      },
      {
        "id": "below_threshold",
        "transform": "compare",
        "left": "{{step.extracted_confidence}}",
        "operator": "less",
        "right": "{{config.confidence_threshold}}"
      },
      {
        "id": "missing_statement",
        "transform": "compare",
        "left": "{{step.extracted_statement}}",
        "operator": "is_empty"
      },
      {
        "id": "skip_create",
        "transform": "any",
        "values": [
          "{{step.skip_empty}}",
          "{{step.below_threshold}}",
          "{{step.missing_statement}}"
        ]
      },
      {
        "id": "resolve_counterparty",
        "skip_when": "{{step.counterparty_email}} is_empty",
        "op": "core.contact.resolve",
        "args": {
          "email": "{{step.counterparty_email}}"
        }
      },
      {
        "id": "create",
        "skip_when": "{{step.skip_create}} equal true",
        "op": "core.work-entity.commitment.create",
        "args": {
          "direction": "{{step.extracted_direction}}",
          "statement": "{{step.extracted_statement}}",
          "derivation": "mail_extracted",
          "promised_for_at": "{{step.promised_for_at}}",
          "expiry_policy": "escalate_overdue",
          "derivation_confidence": "{{step.extracted_confidence}}",
          "monetary_value": "{{step.monetary_value}}",
          "counterparty_contact_id": "{{step.resolve_counterparty.contact.email}}",
          "derived_from_mail_thread_id": "{{step.thread_id}}"
        }
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Mail thread",
            "value": "{{step.thread_id}}"
          },
          {
            "label": "Subject",
            "value": "{{step.subject}}"
          },
          {
            "label": "Statement",
            "value": "{{step.extracted_statement}}"
          },
          {
            "label": "Direction",
            "value": "{{step.extracted_direction}}"
          },
          {
            "label": "Confidence",
            "value": "{{step.extracted_confidence:number}}"
          },
          {
            "label": "Counterparty email",
            "value": "{{step.extracted_counterparty_email}}"
          },
          {
            "label": "Counterparty contact",
            "value": "{{step.resolve_counterparty.contact.email}}"
          },
          {
            "label": "Monetary amount",
            "value": "{{step.extracted_monetary_amount}}"
          },
          {
            "label": "Monetary currency",
            "value": "{{step.extracted_monetary_currency}}"
          },
          {
            "label": "Skipped",
            "value": "{{step.skip_create}}"
          },
          {
            "label": "Commitment ID",
            "value": "{{step.create.commitment.id}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "extract-tasks-from-mail": {
    "recipe_id": "extract-tasks-from-mail",
    "chat_exposed": true,
    "version": 1,
    "ttl": 60,
    "metadata": {
      "name": "Extract tasks from mail (D-145 PA10)",
      "description": "Extract action items from an inbound email into Recued's task tracker — title, due date, and priority (low / medium / high). Thread-aware; fires automatically on each inbound message; records only extractions above the confidence floor (default 0.7). A task is assigned to a contact only when the mail explicitly delegates it to a named third party — otherwise it lands unassigned. The extractor model sees only PII-aliased text, never the raw sender.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "email",
        "mail",
        "task",
        "work-entity",
        "reactive",
        "silent-producer",
        "pack:personal-organizer",
        "ai_surface"
      ],
      "budget_ms": 30000
    },
    "variables": {
      "confidence_threshold": {
        "label": "Minimum extraction confidence (0..1) to create a task row",
        "type": "number",
        "default": 0.7
      },
      "container_names": {
        "label": "Destination container",
        "type": "object",
        "optional": true,
        "default": {},
        "help": "Optional. File the extracted task(s) in a named vendor container, keyed by its dependency ref: { 'project': 'Roadmap' } (Asana) or { 'team': 'Core' } (Linear). Leave empty to use the Source's default destination."
      }
    },
    "requires": [],
    "event_triggers": [
      {
        "event": "data.mail.**.created"
      }
    ],
    "prefetch_steps": [
      {
        "id": "message",
        "op": "core.mail.get",
        "args": {
          "slug": "{{context.event.payload.slug}}",
          "record_id": "{{context.event.payload.record_id}}"
        }
      }
    ],
    "steps": [
      {
        "id": "subject",
        "transform": "default",
        "value": "{{step.message.record.hot_fields.subject}}",
        "fallback": ""
      },
      {
        "id": "from_email",
        "transform": "default",
        "value": "{{step.message.record.hot_fields.from}}",
        "fallback": ""
      },
      {
        "id": "thread_id",
        "transform": "default",
        "value": "{{step.message.record.hot_fields.thread_id}}",
        "fallback": ""
      },
      {
        "id": "has_thread_id",
        "transform": "compare",
        "left": "{{step.thread_id}}",
        "operator": "is_not_empty"
      },
      {
        "id": "thread",
        "skip_when": "{{step.has_thread_id}} not_equal true",
        "op": "core.mail.thread-read",
        "args": {
          "slug": "{{context.event.payload.slug}}",
          "thread_id": "{{step.thread_id}}",
          "max_messages": 5
        }
      },
      {
        "id": "thread_messages",
        "transform": "default",
        "value": "{{step.thread.messages}}",
        "fallback": []
      },
      {
        "id": "thread_body_reads",
        "op": "core.mail.body-read",
        "foreach": "{{step.thread_messages}}",
        "args": {
          "slug": "{{context.event.payload.slug}}",
          "record_id": "{{item.record_id}}",
          "max_chars": 32000
        }
      },
      {
        "id": "thread_messages_with_body",
        "transform": "filter",
        "array": "{{step.thread_body_reads}}",
        "field": "result.body",
        "operator": "is_not_empty"
      },
      {
        "id": "thread_body_segments",
        "transform": "pluck",
        "array": "{{step.thread_messages_with_body}}",
        "field": "result.body"
      },
      {
        "id": "thread_body",
        "transform": "join",
        "array": "{{step.thread_body_segments}}",
        "separator": "\n\n---\n\n"
      },
      {
        "id": "single_body_read",
        "skip_when": "{{step.has_thread_id}} equal true",
        "op": "core.mail.body-read",
        "args": {
          "slug": "{{context.event.payload.slug}}",
          "record_id": "{{context.event.payload.record_id}}",
          "max_chars": 32000
        }
      },
      {
        "id": "single_body",
        "transform": "default",
        "value": "{{step.single_body_read.body}}",
        "fallback": ""
      },
      {
        "id": "body",
        "transform": "ternary",
        "if": "{{step.has_thread_id}}",
        "then": "{{step.thread_body}}",
        "else": "{{step.single_body}}"
      },
      {
        "id": "body_present",
        "transform": "compare",
        "left": "{{step.body}}",
        "operator": "is_not_empty"
      },
      {
        "id": "skip_empty",
        "transform": "compare",
        "left": "{{step.body_present}}",
        "operator": "not_equal",
        "right": true
      },
      {
        "id": "protect",
        "transform": "pii-protect",
        "data": {
          "from": "{{step.from_email}}",
          "subject": "{{step.subject}}",
          "body": "{{step.body}}"
        },
        "fields": [
          {
            "path": "from",
            "kind": "email"
          },
          {
            "path": "subject",
            "kind": "content"
          },
          {
            "path": "body",
            "kind": "content"
          }
        ]
      },
      {
        "id": "extract",
        "skip_when": "{{step.skip_empty}} equal true",
        "op": "core.ai.extract",
        "args": {
          "llm.data": "Subject: {{step.protect.aliased.subject}}\n\n{{step.protect.aliased.body}}\n\n[Field guidance] delegated_assignee_email: the email address of a specific named person this message EXPLICITLY delegates the task to. Return null if the task is directed at the reader/recipient, is a general request, or names no third-party owner — and never use the sender's own signature address.",
          "llm.fields": [
            "title",
            "due_at_iso",
            "priority",
            "delegated_assignee_email",
            "extraction_confidence"
          ],
          "llm.model_hint": "fast"
        }
      },
      {
        "id": "restore",
        "transform": "pii-restore",
        "data": "{{step.extract}}",
        "ledger_handle": "{{step.protect.ledger_handle}}"
      },
      {
        "id": "extracted_title",
        "transform": "default",
        "value": "{{step.restore.restored.title}}",
        "fallback": ""
      },
      {
        "id": "extracted_priority",
        "transform": "default",
        "value": "{{step.restore.restored.priority}}",
        "fallback": "medium"
      },
      {
        "id": "extracted_confidence",
        "transform": "default",
        "value": "{{step.restore.restored.extraction_confidence}}",
        "fallback": 0
      },
      {
        "id": "extracted_assignee_email",
        "transform": "default",
        "value": "{{step.restore.restored.delegated_assignee_email}}",
        "fallback": ""
      },
      {
        "id": "assignee_email",
        "transform": "trim",
        "input": "{{step.extracted_assignee_email}}"
      },
      {
        "id": "due_at",
        "transform": "date_parse",
        "input": "{{step.restore.restored.due_at_iso}}"
      },
      {
        "id": "below_threshold",
        "transform": "compare",
        "left": "{{step.extracted_confidence}}",
        "operator": "less",
        "right": "{{config.confidence_threshold}}"
      },
      {
        "id": "missing_title",
        "transform": "compare",
        "left": "{{step.extracted_title}}",
        "operator": "is_empty"
      },
      {
        "id": "skip_create",
        "transform": "any",
        "values": [
          "{{step.skip_empty}}",
          "{{step.below_threshold}}",
          "{{step.missing_title}}"
        ]
      },
      {
        "id": "resolve_assignee",
        "skip_when": "{{step.assignee_email}} is_empty",
        "op": "core.contact.resolve",
        "args": {
          "email": "{{step.assignee_email}}"
        }
      },
      {
        "id": "create",
        "skip_when": "{{step.skip_create}} equal true",
        "op": "core.work-entity.task.create",
        "args": {
          "title": "{{step.extracted_title}}",
          "due_at": "{{step.due_at}}",
          "priority": "{{step.extracted_priority}}",
          "assigned_contact_id": "{{step.resolve_assignee.contact.email}}",
          "linked_mail_thread_id": "{{step.thread_id}}",
          "container_names": "{{config.container_names}}"
        }
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Mail thread",
            "value": "{{step.thread_id}}"
          },
          {
            "label": "Subject",
            "value": "{{step.subject}}"
          },
          {
            "label": "Task title",
            "value": "{{step.extracted_title}}"
          },
          {
            "label": "Priority",
            "value": "{{step.extracted_priority}}"
          },
          {
            "label": "Confidence",
            "value": "{{step.extracted_confidence:number}}"
          },
          {
            "label": "Assignee email",
            "value": "{{step.extracted_assignee_email}}"
          },
          {
            "label": "Assignee contact",
            "value": "{{step.resolve_assignee.contact.email}}"
          },
          {
            "label": "Skipped",
            "value": "{{step.skip_create}}"
          },
          {
            "label": "Task ID",
            "value": "{{step.create.task.id}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "open-commitments": {
    "recipe_id": "open-commitments",
    "chat_exposed": true,
    "version": 1,
    "ttl": 60,
    "metadata": {
      "name": "Open commitments (D-145 PA10)",
      "description": "Dashboard of open commitments and tasks per contact and project, sorted by each contact's follow-through reliability — dependable counterparties land on top so the easy wins get chased first. Auto-refreshes weekday morning and early afternoon; invoke any time for the current view.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "productivity",
        "commitment",
        "open-loop",
        "dashboard",
        "ai_surface",
        "reactive",
        "pack:personal-organizer"
      ],
      "budget_ms": 30000
    },
    "variables": {
      "open_loop_limit": {
        "label": "Max open-loop entries to surface",
        "type": "number",
        "default": 10
      },
      "start_hour": {
        "label": "Window start hour (local TZ)",
        "type": "number",
        "default": 8
      },
      "end_hour": {
        "label": "Window end hour (local TZ)",
        "type": "number",
        "default": 18
      }
    },
    "requires": [],
    "auto_run": {
      "interval_ms": 600000
    },
    "trigger_steps": [
      {
        "id": "active_window",
        "op": "core.watch.time",
        "args": {
          "weekdays": [
            1,
            2,
            3,
            4,
            5
          ],
          "start_hour": "{{config.start_hour}}",
          "end_hour": "{{config.end_hour}}"
        }
      }
    ],
    "prefetch_steps": [
      {
        "id": "open_loops",
        "op": "core.data.enrichment.list",
        "args": {
          "topic": "open_loop_pressure",
          "scope": "contact",
          "limit": "{{config.open_loop_limit}}"
        }
      },
      {
        "id": "reliability_bands",
        "op": "core.data.enrichment.list",
        "args": {
          "topic": "commitment_reliability_band",
          "scope": "contact",
          "limit": "{{config.open_loop_limit}}"
        }
      }
    ],
    "steps": [
      {
        "id": "open_loop_count",
        "transform": "count",
        "input": "{{step.open_loops.entries}}"
      },
      {
        "id": "reliability_count",
        "transform": "count",
        "input": "{{step.reliability_bands.entries}}"
      },
      {
        "id": "open_loop_targets",
        "transform": "pluck",
        "array": "{{step.open_loops.entries}}",
        "field": "target_id"
      },
      {
        "id": "open_loop_text",
        "transform": "join",
        "array": "{{step.open_loop_targets}}",
        "separator": ", "
      },
      {
        "id": "high_reliability",
        "transform": "filter",
        "array": "{{step.reliability_bands.entries}}",
        "field": "value.band",
        "operator": "equal",
        "value": "high"
      },
      {
        "id": "mid_reliability",
        "transform": "filter",
        "array": "{{step.reliability_bands.entries}}",
        "field": "value.band",
        "operator": "equal",
        "value": "mid"
      },
      {
        "id": "low_reliability",
        "transform": "filter",
        "array": "{{step.reliability_bands.entries}}",
        "field": "value.band",
        "operator": "equal",
        "value": "low"
      },
      {
        "id": "high_reliability_targets",
        "transform": "pluck",
        "array": "{{step.high_reliability}}",
        "field": "target_id"
      },
      {
        "id": "mid_reliability_targets",
        "transform": "pluck",
        "array": "{{step.mid_reliability}}",
        "field": "target_id"
      },
      {
        "id": "low_reliability_targets",
        "transform": "pluck",
        "array": "{{step.low_reliability}}",
        "field": "target_id"
      },
      {
        "id": "high_reliability_text",
        "transform": "join",
        "array": "{{step.high_reliability_targets}}",
        "separator": ", "
      },
      {
        "id": "mid_reliability_text",
        "transform": "join",
        "array": "{{step.mid_reliability_targets}}",
        "separator": ", "
      },
      {
        "id": "low_reliability_text",
        "transform": "join",
        "array": "{{step.low_reliability_targets}}",
        "separator": ", "
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Open-loop contacts",
            "value": "{{step.open_loop_count:number}}"
          },
          {
            "label": "Reliability rows scanned",
            "value": "{{step.reliability_count:number}}"
          },
          {
            "label": "High-reliability follow-ups (chase first)",
            "value": "{{step.high_reliability_text}}"
          },
          {
            "label": "Mid-reliability follow-ups (standard chase)",
            "value": "{{step.mid_reliability_text}}"
          },
          {
            "label": "Low-reliability follow-ups (long-tail)",
            "value": "{{step.low_reliability_text}}"
          },
          {
            "label": "All open-loop targets",
            "value": "{{step.open_loop_text}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "recent-notes-by-topic": {
    "recipe_id": "recent-notes-by-topic",
    "chat_exposed": true,
    "version": 1,
    "ttl": 60,
    "metadata": {
      "name": "Recent notes by topic (D-145 PA10)",
      "description": "Surface your still-warm notes: ranks notes by ongoing relevance (recently touched and frequently referenced rise; dormant ones decay over 180 days) and shows the freshest decile. Private notes stay private by default. Auto-refreshes weekday mornings.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "productivity",
        "note",
        "recent",
        "dashboard",
        "ai_surface",
        "reactive",
        "pack:personal-organizer"
      ],
      "budget_ms": 30000
    },
    "variables": {
      "note_limit": {
        "label": "Max recent-notes entries to surface",
        "type": "number",
        "default": 10
      }
    },
    "requires": [],
    "auto_run": {
      "interval_ms": 600000
    },
    "trigger_steps": [
      {
        "id": "morning_window",
        "op": "core.watch.time",
        "args": {
          "weekdays": [
            1,
            2,
            3,
            4,
            5
          ],
          "start_hour": 8,
          "end_hour": 9
        }
      }
    ],
    "prefetch_steps": [
      {
        "id": "relevance_rows",
        "op": "core.data.enrichment.list",
        "args": {
          "topic": "note_relevance_decay",
          "scope": "note",
          "limit": "{{config.note_limit}}"
        }
      }
    ],
    "steps": [
      {
        "id": "row_count",
        "transform": "count",
        "input": "{{step.relevance_rows.entries}}"
      },
      {
        "id": "note_ids",
        "transform": "pluck",
        "array": "{{step.relevance_rows.entries}}",
        "field": "target_id"
      },
      {
        "id": "note_ids_text",
        "transform": "join",
        "array": "{{step.note_ids}}",
        "separator": ", "
      },
      {
        "id": "first_note_id",
        "transform": "default",
        "value": "{{step.relevance_rows.entries.0.target_id}}",
        "fallback": ""
      },
      {
        "id": "first_relevance_score",
        "transform": "default",
        "value": "{{step.relevance_rows.entries.0.value.relevance_score}}",
        "fallback": 0
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Recent notes (relevance-ranked)",
            "value": "{{step.row_count:number}}"
          },
          {
            "label": "Top note ID",
            "value": "{{step.first_note_id}}"
          },
          {
            "label": "Top note relevance",
            "value": "{{step.first_relevance_score:number}}"
          },
          {
            "label": "All recent note IDs",
            "value": "{{step.note_ids_text}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "remind-me-of": {
    "recipe_id": "remind-me-of",
    "chat_exposed": true,
    "version": 1,
    "ttl": 60,
    "metadata": {
      "name": "Remind me",
      "description": "Capture a one-shot personal reminder as a Recued task. Resolve the requested time against the current date/time in your context, in the user's timezone, and pass remind_at as an absolute ISO 8601 timestamp with an explicit offset. The paired reminder-due-notifier recipe fans notification delivery through the user's configured channels.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "reminder",
        "task",
        "notify",
        "personal-organizer",
        "pack:personal-organizer"
      ],
      "budget_ms": 10000
    },
    "variables": {
      "reminder_text": {
        "label": "Reminder text",
        "type": "string",
        "help": "Bare reminder text to show when the reminder fires."
      },
      "remind_at": {
        "label": "Remind at",
        "type": "datetime",
        "help": "When the reminder should fire, as an absolute ISO 8601 / RFC 3339 date-time WITH a timezone offset (e.g. 2026-07-04T15:00:00-07:00 or 2026-07-04T22:00:00Z). Resolve the user's requested time against the current date/time in your context, in the user's timezone — do NOT assume UTC; if the timezone is unknown, ask before guessing. An offset-less value is rejected."
      },
      "container_names": {
        "label": "Destination container",
        "type": "object",
        "optional": true,
        "default": {},
        "help": "Optional. File the reminder in a named vendor container, keyed by its dependency ref: { 'project': 'Roadmap' } (Asana) or { 'team': 'Core' } (Linear). Leave empty to use the Source's default destination."
      }
    },
    "requires": [],
    "steps": [
      {
        "id": "text",
        "transform": "trim",
        "input": "{{config.reminder_text}}"
      },
      {
        "id": "due_at_ms",
        "transform": "date_parse",
        "input": "{{config.remind_at}}",
        "require_offset": true,
        "fail_on": "{{step.due_at_ms}} is_null"
      },
      {
        "id": "create",
        "op": "core.work-entity.task.create",
        "args": {
          "title": "Reminder: {{step.text}}",
          "body": "{{step.text}}",
          "due_at": "{{step.due_at_ms}}",
          "state": "reminder_pending",
          "source_extension_blob": {
            "kind": "recued_reminder"
          },
          "container_names": "{{config.container_names}}"
        }
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Reminder",
            "value": "{{step.text}}"
          },
          {
            "label": "Due at",
            "value": "{{config.remind_at}}"
          },
          {
            "label": "Task ID",
            "value": "{{step.create.task._id}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "reminder-due-notifier": {
    "recipe_id": "reminder-due-notifier",
    "chat_exposed": false,
    "version": 1,
    "ttl": 60,
    "metadata": {
      "name": "Reminder due notifier",
      "description": "Hidden reminder firing recipe. It watches Recued reminder tasks at due_at, sends a notification through default fanout, and marks the task state as fired so the reminder does not re-notify after the watcher ledger has fired.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "reminder",
        "task",
        "notify",
        "reactive",
        "hidden",
        "pack:personal-organizer"
      ],
      "budget_ms": 10000
    },
    "variables": {},
    "requires": [
      "notification_send"
    ],
    "auto_run": {
      "interval_ms": 60000,
      "dynamic": false
    },
    "trigger_steps": [
      {
        "id": "due",
        "op": "core.watch.time-relative",
        "args": {
          "collection": "data.task",
          "anchor_field": "due_at",
          "offsets": [
            "0s"
          ],
          "filter": "recued_reminder"
        }
      }
    ],
    "steps": [
      {
        "id": "text",
        "transform": "default",
        "value": "{{trigger.due.trigger_record.body}}",
        "fallback": "{{trigger.due.trigger_record.title}}"
      },
      {
        "id": "skip_notification",
        "transform": "any",
        "conditions": [
          "{{trigger.due.trigger_record.state}} not_equal reminder_pending",
          "{{trigger.due.trigger_record.done}} equal true"
        ]
      },
      {
        "id": "send",
        "skip_when": "{{step.skip_notification}} equal true",
        "op": "core.notification.send",
        "args": {
          "title": "Reminder",
          "text": "{{step.text}}",
          "link_url": null
        }
      },
      {
        "id": "delivery_not_confirmed",
        "transform": "any",
        "conditions": [
          "{{step.skip_notification}} equal true",
          "{{step.send.delivered_to}} is_empty"
        ]
      },
      {
        "id": "mark_fired",
        "skip_when": "{{step.delivery_not_confirmed}} equal true",
        "op": "core.work-entity.task.update",
        "args": {
          "id": "{{trigger.due.trigger_record_id}}",
          "state": "reminder_fired"
        }
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Reminder",
            "value": "{{step.text}}"
          },
          {
            "label": "Task ID",
            "value": "{{trigger.due.trigger_record_id}}"
          },
          {
            "label": "Delivered to",
            "value": "{{step.send.delivered_to}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "reschedule-booking": {
    "recipe_id": "reschedule-booking",
    "chat_exposed": false,
    "version": 1,
    "ttl": 60,
    "requires": [],
    "metadata": {
      "name": "Reschedule a booking",
      "description": "D-210 R-4 / A.2 — the owner's reschedule ignition for a BOOKING. Moves one data.booking row to a new slot via a single booking-update patch carrying slot_start_at AND slot_end_at. Deterministic: the owner picks the time (no AI writes it — LLM-as-editor is out of scope). A booking owns its own time and is never in the calendar (A.2), so this is how a reservation moves — there is no calendar event to update instead. The pair moves ATOMICALLY: booking-update refuses a half-supplied move, because keeping the old end against a new start would silently change the booking's duration. Triggered manually with config {booking_id, new_start_at, new_end_at} (unix ms) — the webclient reschedule control on a booking record fills them from the row's own slot, computing the new end from the current duration. Telling the visitor is an OWNER TICK on this run, not a trigger: set notify_visitor (and sender_mail_instance) and this recipe mails them that the booking moved. It is off unless the owner turns it on for this reschedule — a message to someone else is a judgement the owner makes per occasion. The address is never an argument and never reaches step state: notify-booking-visitor resolves it server-side from the booking's own reception_record_id, and does nothing (notified:false) when the booking did not come from a reception request. ⚠ This REPLACES a claim that a reactive notify-visitor-on-reschedule recipe did it on approval — that recipe had no trigger, no booking_id and no subscribers, so it could never fire (D-210 code audit finding 4). Re-running the same move is safe (the patch is idempotent and preserves the booking's identity, lifecycle_state and provenance).",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "calendar",
        "reschedule",
        "booking",
        "reception",
        "notify"
      ],
      "budget_ms": 30000
    },
    "variables": {
      "booking_id": {
        "label": "Booking id",
        "type": "string",
        "default": ""
      },
      "new_start_at": {
        "label": "New start (unix ms)",
        "type": "number",
        "default": null
      },
      "new_end_at": {
        "label": "New end (unix ms)",
        "type": "number",
        "default": null
      },
      "notify_visitor": {
        "label": "Tell the visitor their booking moved",
        "type": "boolean",
        "default": false
      },
      "sender_mail_instance": {
        "label": "Send from (data.mail account)",
        "type": "string",
        "default": ""
      }
    },
    "steps": [
      {
        "id": "ready",
        "transform": "all",
        "conditions": [
          "{{config.booking_id}} is_not_empty",
          "{{config.new_start_at}} is_not_null",
          "{{config.new_end_at}} is_not_null"
        ]
      },
      {
        "id": "reschedule",
        "skip_when": "{{step.ready}} not_equal true",
        "op": "core.work-entity.booking.update",
        "args": {
          "id": "{{config.booking_id}}",
          "slot_start_at": "{{config.new_start_at}}",
          "slot_end_at": "{{config.new_end_at}}"
        }
      },
      {
        "id": "moved",
        "transform": "compare",
        "left": "{{step.reschedule.booking.id}}",
        "operator": "is_not_null"
      },
      {
        "id": "new_time",
        "transform": "date_format",
        "date": "{{config.new_start_at}}",
        "format": "YYYY-MM-DD HH:mm"
      },
      {
        "id": "notify_ready",
        "transform": "all",
        "conditions": [
          "{{config.notify_visitor}} equal true",
          "{{step.moved}} equal true",
          "{{config.sender_mail_instance}} is_not_empty"
        ]
      },
      {
        "id": "subject",
        "skip_when": "{{step.notify_ready}} not_equal true",
        "transform": "template",
        "template": "Your booking has moved to {{step.new_time}}"
      },
      {
        "id": "body",
        "skip_when": "{{step.notify_ready}} not_equal true",
        "transform": "template",
        "template": "Hi — the time for your booking has changed. It is now {{step.new_time}}. If the new time does not work for you, just reply to this message and we will sort it out."
      },
      {
        "id": "notify",
        "skip_when": "{{step.notify_ready}} not_equal true",
        "op": "core.mail.notify-booking-visitor",
        "args": {
          "booking_id": "{{config.booking_id}}",
          "sender_mail_instance": "{{config.sender_mail_instance}}",
          "subject": "{{step.subject}}",
          "body": "{{step.body}}"
        }
      },
      {
        "id": "visitor_told",
        "transform": "default",
        "value": "{{step.notify.notified}}",
        "fallback": false
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Booking",
            "value": "{{config.booking_id}}"
          },
          {
            "label": "Rescheduled",
            "value": "{{step.moved}}"
          },
          {
            "label": "New start",
            "value": "{{config.new_start_at:date}}"
          },
          {
            "label": "New end",
            "value": "{{config.new_end_at:date}}"
          },
          {
            "label": "Visitor told",
            "value": "{{step.visitor_told}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "reschedule-booking-managed": {
    "recipe_id": "reschedule-booking-managed",
    "chat_exposed": false,
    "version": 1,
    "ttl": 60,
    "requires": [],
    "metadata": {
      "name": "Reschedule a booking (managed door)",
      "description": "D-210 Appendix B — the RESCHEDULE ignition for the public /reception/manage door. Identical write to reschedule-booking (one core.work-entity.booking.update patching slot_start_at + slot_end_at) but WITHOUT an output.render block, so it can back a public reception door: a door whose recipe renders output cannot carry a write (bindReceptionDoor refuses it — an anonymous write holds and returns no output, so the visitor would get a bare page). Here the manage HANDLER owns the response (the held-request page), not the recipe, so the recipe renders nothing. Run by the manage handler under the anonymous reception actor + the door's minted contract: the booking-update write is pinned to the read ceiling and HOLDS at the D-157 gate — the owner approves it in the Reception Inbox (or on the go). config {booking_id, new_start_at, new_end_at} (unix ms) is supplied per-request by the manage handler — the TARGET (booking_id) is resolved server-side from the credential (a visitor cannot retarget), only the new time comes from the form. ⚠ The visitor is NOT auto-notified here, and that is deliberate: on this door the VISITOR asked for the move, so they already know. This used to claim a reactive notify-visitor-on-reschedule recipe told them on approval — that recipe had no trigger, no booking_id and no subscribers, so it could never fire (D-210 code audit finding 4). If the owner approves a DIFFERENT time than the visitor asked for, telling them is a deliberate act: run reschedule-booking with notify_visitor set. The slot pair moves ATOMICALLY: booking-update refuses a half-supplied move, so a re-run of the same times is safe and a partial one is impossible.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "calendar",
        "reschedule",
        "booking",
        "reception",
        "managed-door"
      ],
      "budget_ms": 30000
    },
    "variables": {
      "booking_id": {
        "label": "Booking id",
        "type": "string",
        "default": ""
      },
      "new_start_at": {
        "label": "New start (unix ms)",
        "type": "number",
        "default": null
      },
      "new_end_at": {
        "label": "New end (unix ms)",
        "type": "number",
        "default": null
      }
    },
    "steps": [
      {
        "id": "ready",
        "transform": "all",
        "conditions": [
          "{{config.booking_id}} is_not_empty",
          "{{config.new_start_at}} is_not_null",
          "{{config.new_end_at}} is_not_null"
        ]
      },
      {
        "id": "manage_target_booking_id",
        "transform": "coalesce",
        "values": [
          "{{config.booking_id}}",
          ""
        ]
      },
      {
        "id": "reschedule",
        "skip_when": "{{step.ready}} not_equal true",
        "op": "core.work-entity.booking.update",
        "args": {
          "id": "{{config.booking_id}}",
          "slot_start_at": "{{config.new_start_at}}",
          "slot_end_at": "{{config.new_end_at}}"
        }
      }
    ],
    "output": {
      "render": []
    }
  },
  "reschedule-calendar-event": {
    "recipe_id": "reschedule-calendar-event",
    "chat_exposed": false,
    "version": 1,
    "ttl": 60,
    "requires": [],
    "metadata": {
      "name": "Reschedule a calendar event",
      "description": "D-210 R-4 — the owner's reschedule ignition for a PERSONAL calendar event. Moves ONE calendar event to a new start/end time via a single calendar-update patch. Deterministic: the owner picks the time (no AI writes it — LLM-as-editor is out of scope). ⚠ This does NOT move a booking. Since D-210 A.2 a booking is never in the calendar — it owns its own slot_start_at / slot_end_at — so a reservation is rescheduled with reschedule-booking instead, and only that path notifies the visitor. Triggered manually with config {calendar_slug, event_source_id, new_start_at, new_end_at} (unix ms) — the webclient reschedule control on a calendar record fills them from the event's own record, computing the new end from the current duration. calendar-update is idempotent and preserves the event's identity, so re-running the same move is safe.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "calendar",
        "reschedule",
        "booking",
        "reception",
        "owner-action"
      ],
      "budget_ms": 20000
    },
    "variables": {
      "calendar_slug": {
        "label": "Calendar instance slug",
        "type": "string",
        "default": ""
      },
      "event_source_id": {
        "label": "Event source id",
        "type": "string",
        "default": ""
      },
      "new_start_at": {
        "label": "New start (unix ms)",
        "type": "number",
        "default": null
      },
      "new_end_at": {
        "label": "New end (unix ms)",
        "type": "number",
        "default": null
      }
    },
    "steps": [
      {
        "id": "ready",
        "transform": "all",
        "conditions": [
          "{{config.calendar_slug}} is_not_empty",
          "{{config.event_source_id}} is_not_empty",
          "{{config.new_start_at}} is_not_null",
          "{{config.new_end_at}} is_not_null"
        ]
      },
      {
        "id": "reschedule",
        "skip_when": "{{step.ready}} not_equal true",
        "op": "core.data.calendar.update",
        "args": {
          "slug": "{{config.calendar_slug}}",
          "source_id": "{{config.event_source_id}}",
          "patch": {
            "start_at": "{{config.new_start_at}}",
            "end_at": "{{config.new_end_at}}"
          }
        }
      },
      {
        "id": "moved",
        "transform": "compare",
        "left": "{{step.reschedule.source_id}}",
        "operator": "is_not_null"
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Event",
            "value": "{{config.event_source_id}}"
          },
          {
            "label": "Rescheduled",
            "value": "{{step.moved}}"
          },
          {
            "label": "New start",
            "value": "{{config.new_start_at:date}}"
          },
          {
            "label": "New end",
            "value": "{{config.new_end_at:date}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "schedule-recipe": {
    "recipe_id": "schedule-recipe",
    "chat_exposed": true,
    "version": 1,
    "ttl": 60,
    "metadata": {
      "name": "Schedule recipe",
      "description": "Create a recurring or one-shot schedule for an already installed Recued recipe. Accepts only an installed recipe_id plus timing fields — no inline recipe JSON or new steps. For one_shot, resolve run_at against the current date/time in your context, in the user's timezone, as an absolute ISO 8601 timestamp with an explicit offset.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "schedule",
        "recipe",
        "automation",
        "control-plane",
        "productivity",
        "pack:personal-organizer"
      ],
      "budget_ms": 10000
    },
    "variables": {
      "recipe_id": {
        "label": "Recipe ID",
        "type": "string",
        "help": "Installed recipe_id to schedule."
      },
      "mode": {
        "label": "Schedule mode",
        "type": "enum",
        "options": [
          "one_shot",
          "recurring"
        ],
        "help": "Use one_shot for a single future run, recurring for a cron schedule."
      },
      "run_at": {
        "label": "Run at",
        "type": "datetime",
        "optional": true,
        "help": "Required for one_shot: when the recipe runs, as an absolute ISO 8601 / RFC 3339 date-time WITH a timezone offset (e.g. 2026-07-04T15:00:00-07:00 or 2026-07-04T22:00:00Z). Resolve the user's requested time against the current date/time in your context, in the user's timezone — do NOT assume UTC; if the timezone is unknown, ask. An offset-less value is rejected."
      },
      "cron_expression": {
        "label": "Cron expression",
        "type": "string",
        "optional": true,
        "default": "",
        "help": "Required for recurring. Five-field cron expression."
      },
      "dish_id": {
        "label": "Dish ID",
        "type": "string",
        "optional": true,
        "default": "",
        "help": "Optional standing dish binding for overlay and continuity."
      },
      "enabled": {
        "label": "Enabled",
        "type": "boolean",
        "default": true,
        "help": "Whether the schedule should be armed immediately."
      }
    },
    "requires": [],
    "steps": [
      {
        "id": "run_at_ms",
        "skip_when": "{{config.mode}} not_equal one_shot",
        "transform": "date_parse",
        "input": "{{config.run_at}}",
        "require_offset": true,
        "fail_on": "{{step.run_at_ms}} is_null"
      },
      {
        "id": "create",
        "op": "core.schedule.recipe",
        "args": {
          "recipe_id": "{{config.recipe_id}}",
          "mode": "{{config.mode}}",
          "run_at": "{{step.run_at_ms}}",
          "cron_expression": "{{config.cron_expression}}",
          "dish_id": "{{config.dish_id}}",
          "enabled": "{{config.enabled}}"
        }
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Recipe",
            "value": "{{config.recipe_id}}"
          },
          {
            "label": "Mode",
            "value": "{{config.mode}}"
          },
          {
            "label": "Schedule ID",
            "value": "{{step.create.schedule.schedule_id}}"
          },
          {
            "label": "Next run",
            "value": "{{step.create.schedule.next_run_at}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "stalled-projects": {
    "recipe_id": "stalled-projects",
    "chat_exposed": true,
    "version": 1,
    "ttl": 60,
    "metadata": {
      "name": "Stalled projects (D-145 PA10)",
      "description": "Today's intervention list for projects: those with no activity past the 14-day stall horizon, plus active projects with no next action (no open task, pending commitment, or recent note) — each with an AI-suggested next step. Auto-refreshes on weekdays.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "productivity",
        "project",
        "stalled",
        "dashboard",
        "ai_surface",
        "reactive",
        "pack:personal-organizer"
      ],
      "budget_ms": 30000
    },
    "variables": {
      "stall_limit": {
        "label": "Max stalled projects to surface",
        "type": "number",
        "default": 8
      }
    },
    "requires": [],
    "auto_run": {
      "interval_ms": 600000
    },
    "trigger_steps": [
      {
        "id": "weekday_window",
        "op": "core.watch.time",
        "args": {
          "weekdays": [
            1,
            2,
            3,
            4,
            5
          ],
          "start_hour": 8,
          "end_hour": 18
        }
      }
    ],
    "prefetch_steps": [
      {
        "id": "stall_signals",
        "op": "core.data.enrichment.list",
        "args": {
          "topic": "project_stall_signal",
          "scope": "project",
          "limit": "{{config.stall_limit}}"
        }
      },
      {
        "id": "next_action_gaps",
        "op": "core.data.enrichment.list",
        "args": {
          "topic": "project_next_action_gap",
          "scope": "project",
          "limit": "{{config.stall_limit}}"
        }
      }
    ],
    "steps": [
      {
        "id": "stalled_count",
        "transform": "count",
        "input": "{{step.stall_signals.entries}}"
      },
      {
        "id": "gap_count",
        "transform": "count",
        "input": "{{step.next_action_gaps.entries}}"
      },
      {
        "id": "stalled_ids",
        "transform": "pluck",
        "array": "{{step.stall_signals.entries}}",
        "field": "target_id"
      },
      {
        "id": "gap_ids",
        "transform": "pluck",
        "array": "{{step.next_action_gaps.entries}}",
        "field": "target_id"
      },
      {
        "id": "intervention_ids",
        "transform": "flatten",
        "array": [
          "{{step.stalled_ids}}",
          "{{step.gap_ids}}"
        ],
        "depth": 1
      },
      {
        "id": "intervention_unique",
        "transform": "unique",
        "array": "{{step.intervention_ids}}"
      },
      {
        "id": "intervention_count",
        "transform": "count",
        "input": "{{step.intervention_unique}}"
      },
      {
        "id": "intervention_text",
        "transform": "join",
        "array": "{{step.intervention_unique}}",
        "separator": ", "
      },
      {
        "id": "any_intervention",
        "transform": "compare",
        "left": "{{step.intervention_count}}",
        "operator": "greater",
        "right": 0
      },
      {
        "id": "next_action_prompt",
        "skip_when": "{{step.any_intervention}} not_equal true",
        "op": "core.ai.generate",
        "args": {
          "llm.data": "Projects with no recent activity or no next action: {{step.intervention_text}}",
          "llm.template_type": "next_action_prompt",
          "llm.tone": "concise",
          "llm.model_hint": "fast"
        }
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Stall-signaled projects",
            "value": "{{step.stalled_count:number}}"
          },
          {
            "label": "Projects with no next action",
            "value": "{{step.gap_count:number}}"
          },
          {
            "label": "Intervention list (union)",
            "value": "{{step.intervention_text}}"
          },
          {
            "label": "Suggested next-action prompt",
            "value": "{{step.next_action_prompt.content}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "today": {
    "recipe_id": "today",
    "chat_exposed": true,
    "version": 1,
    "ttl": 60,
    "metadata": {
      "name": "Today (D-145 PA10)",
      "description": "Morning glance card: today's calendar, the contacts and projects carrying the most open loops (unresolved commitments, tasks, unanswered threads), and active projects with no next action. Auto-refreshes weekday mornings (window configurable via start_hour / end_hour); invoke any time for a fresh snapshot.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "morning",
        "dashboard",
        "calendar",
        "commitments",
        "tasks",
        "ai_surface",
        "reactive",
        "pack:personal-organizer"
      ],
      "budget_ms": 30000
    },
    "variables": {
      "calendar_slug": {
        "label": "Primary calendar slug to read today's events from",
        "type": "string",
        "default": "primary"
      },
      "start_hour": {
        "label": "Window start hour (local TZ)",
        "type": "number",
        "default": 8
      },
      "end_hour": {
        "label": "Window end hour (local TZ)",
        "type": "number",
        "default": 9
      },
      "weekdays": {
        "label": "Active weekdays (1=Mon..7=Sun)",
        "type": "array",
        "default": [
          1,
          2,
          3,
          4,
          5
        ]
      },
      "open_loop_limit": {
        "label": "Max open-loop entries to surface",
        "type": "number",
        "default": 5
      }
    },
    "requires": [],
    "auto_run": {
      "interval_ms": 600000
    },
    "trigger_steps": [
      {
        "id": "morning",
        "op": "core.watch.time",
        "args": {
          "weekdays": "{{config.weekdays}}",
          "start_hour": "{{config.start_hour}}",
          "end_hour": "{{config.end_hour}}"
        }
      }
    ],
    "prefetch_steps": [
      {
        "id": "open_loops",
        "op": "core.data.enrichment.list",
        "args": {
          "topic": "open_loop_pressure",
          "limit": "{{config.open_loop_limit}}"
        }
      },
      {
        "id": "project_gaps",
        "op": "core.data.enrichment.list",
        "args": {
          "topic": "project_next_action_gap",
          "scope": "project",
          "limit": "{{config.open_loop_limit}}"
        }
      }
    ],
    "steps": [
      {
        "id": "today_window",
        "transform": "date_period",
        "period": "today"
      },
      {
        "id": "today_start_ms",
        "transform": "date_parse",
        "input": "{{step.today_window.start}}"
      },
      {
        "id": "today_end_ms",
        "transform": "date_parse",
        "input": "{{step.today_window.end}}"
      },
      {
        "id": "calendar_events",
        "op": "core.data.calendar.list",
        "args": {
          "slug": "{{config.calendar_slug}}",
          "since": "{{step.today_start_ms}}",
          "until": "{{step.today_end_ms}}",
          "status": "confirmed"
        }
      },
      {
        "id": "calendar_count",
        "transform": "count",
        "input": "{{step.calendar_events.records}}"
      },
      {
        "id": "open_loop_count",
        "transform": "count",
        "input": "{{step.open_loops.entries}}"
      },
      {
        "id": "gap_count",
        "transform": "count",
        "input": "{{step.project_gaps.entries}}"
      },
      {
        "id": "open_loop_targets",
        "transform": "pluck",
        "array": "{{step.open_loops.entries}}",
        "field": "target_id"
      },
      {
        "id": "open_loop_targets_text",
        "transform": "join",
        "array": "{{step.open_loop_targets}}",
        "separator": ", "
      },
      {
        "id": "gap_targets",
        "transform": "pluck",
        "array": "{{step.project_gaps.entries}}",
        "field": "target_id"
      },
      {
        "id": "gap_targets_text",
        "transform": "join",
        "array": "{{step.gap_targets}}",
        "separator": ", "
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Today calendar events",
            "value": "{{step.calendar_count:number}}"
          },
          {
            "label": "Open-loop contacts/projects",
            "value": "{{step.open_loop_count:number}}"
          },
          {
            "label": "Top open-loop targets",
            "value": "{{step.open_loop_targets_text}}"
          },
          {
            "label": "Active projects without next action",
            "value": "{{step.gap_count:number}}"
          },
          {
            "label": "Top project gaps",
            "value": "{{step.gap_targets_text}}"
          },
          {
            "label": "Window",
            "value": "{{step.today_window.start}} → {{step.today_window.end}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  },
  "triage-inbox": {
    "recipe_id": "triage-inbox",
    "chat_exposed": true,
    "version": 1,
    "ttl": 60,
    "metadata": {
      "name": "Triage inbox (D-145 PA10)",
      "description": "Classify each inbound email into urgent_action / awaiting_response / fyi / promotional / spam and send an in-app notification for urgent_action + awaiting_response (subject, sender, suggested next action). Promotional / spam classify silently — no notification noise on bulk mail. Fires automatically on inbound mail; the classifier model sees only PII-aliased text, never the raw sender.",
      "author": "recued-core",
      "supported_platforms": [],
      "tags": [
        "email",
        "mail",
        "inbox",
        "triage",
        "alert",
        "ai_surface",
        "reactive",
        "pack:personal-organizer"
      ],
      "budget_ms": 30000
    },
    "variables": {
      "channels": {
        "label": "Notification channels",
        "type": "array",
        "default": [
          "in_app"
        ]
      },
      "min_confidence": {
        "label": "Min confidence to notify (0..1)",
        "type": "number",
        "default": 0.6
      }
    },
    "requires": [
      "notification_send"
    ],
    "event_triggers": [
      {
        "event": "data.mail.**.created"
      }
    ],
    "prefetch_steps": [
      {
        "id": "message",
        "op": "core.mail.get",
        "args": {
          "slug": "{{context.event.payload.slug}}",
          "record_id": "{{context.event.payload.record_id}}"
        }
      }
    ],
    "steps": [
      {
        "id": "subject",
        "transform": "default",
        "value": "{{step.message.record.hot_fields.subject}}",
        "fallback": ""
      },
      {
        "id": "from_email",
        "transform": "default",
        "value": "{{step.message.record.hot_fields.from}}",
        "fallback": ""
      },
      {
        "id": "body_read",
        "op": "core.mail.body-read",
        "args": {
          "slug": "{{context.event.payload.slug}}",
          "record_id": "{{context.event.payload.record_id}}",
          "max_chars": 32000
        }
      },
      {
        "id": "body",
        "transform": "default",
        "value": "{{step.body_read.body}}",
        "fallback": ""
      },
      {
        "id": "body_present",
        "transform": "compare",
        "left": "{{step.body}}",
        "operator": "is_not_empty"
      },
      {
        "id": "skip_empty",
        "transform": "compare",
        "left": "{{step.body_present}}",
        "operator": "not_equal",
        "right": true
      },
      {
        "id": "protect",
        "transform": "pii-protect",
        "data": {
          "from": "{{step.from_email}}",
          "subject": "{{step.subject}}",
          "body": "{{step.body}}"
        },
        "fields": [
          {
            "path": "from",
            "kind": "email"
          },
          {
            "path": "subject",
            "kind": "content"
          },
          {
            "path": "body",
            "kind": "content"
          }
        ]
      },
      {
        "id": "classify",
        "skip_when": "{{step.skip_empty}} equal true",
        "op": "core.ai.classify",
        "args": {
          "llm.data": "From: {{step.protect.aliased.from}}\nSubject: {{step.protect.aliased.subject}}\n\n{{step.protect.aliased.body}}",
          "llm.categories": [
            "urgent_action",
            "awaiting_response",
            "fyi",
            "promotional",
            "spam"
          ],
          "llm.context": "Classify the user's inbound mail by what action it implies. urgent_action = caller needs response within 24h; awaiting_response = the user previously promised something now arriving as a follow-up; fyi = informational only; promotional = marketing / newsletter; spam = unsolicited.",
          "llm.model_hint": "fast"
        }
      },
      {
        "id": "restore",
        "transform": "pii-restore",
        "data": {
          "reasoning": "{{step.classify.reasoning}}"
        },
        "ledger_handle": "{{step.protect.ledger_handle}}"
      },
      {
        "id": "category",
        "transform": "default",
        "value": "{{step.classify.category}}",
        "fallback": "fyi"
      },
      {
        "id": "confidence",
        "transform": "default",
        "value": "{{step.classify.confidence}}",
        "fallback": 0
      },
      {
        "id": "is_actionable",
        "transform": "any",
        "conditions": [
          "{{step.category}} equal urgent_action",
          "{{step.category}} equal awaiting_response"
        ]
      },
      {
        "id": "below_confidence",
        "transform": "compare",
        "left": "{{step.confidence}}",
        "operator": "less",
        "right": "{{config.min_confidence}}"
      },
      {
        "id": "skip_notify",
        "transform": "any",
        "conditions": [
          "{{step.skip_empty}} equal true",
          "{{step.below_confidence}} equal true",
          "{{step.is_actionable}} equal false"
        ]
      },
      {
        "id": "notify_title",
        "transform": "switch",
        "input": "{{step.category}}",
        "cases": {
          "urgent_action": "Urgent: {{step.subject}}",
          "awaiting_response": "Awaiting your response: {{step.subject}}"
        },
        "default": "Mail: {{step.subject}}"
      },
      {
        "id": "notify",
        "skip_when": "{{step.skip_notify}} equal true",
        "op": "core.notification.send",
        "args": {
          "channels": "{{config.channels}}",
          "title": "{{step.notify_title}}",
          "text": "From {{step.from_email}}. AI confidence {{step.confidence:percent}}. {{step.restore.restored.reasoning}}",
          "link_url": null
        }
      },
      {
        "id": "card",
        "transform": "to_summary",
        "fields": [
          {
            "label": "Mail thread",
            "value": "{{step.message.record.hot_fields.thread_id}}"
          },
          {
            "label": "From",
            "value": "{{step.from_email}}"
          },
          {
            "label": "Subject",
            "value": "{{step.subject}}"
          },
          {
            "label": "Category",
            "value": "{{step.category}}"
          },
          {
            "label": "Confidence",
            "value": "{{step.confidence:percent}}"
          },
          {
            "label": "Notified",
            "value": "{{step.notify.delivered_to}}"
          },
          {
            "label": "Skipped",
            "value": "{{step.skip_notify}}"
          }
        ]
      }
    ],
    "output": {
      "render": [
        {
          "type": "summary",
          "source": "step.card"
        }
      ]
    }
  }
} as unknown as Readonly<Record<string, RecipeDefinition>>;
