/** D-201 Slices 8A + 8C + 8K + 9P-9W — GitHub profile compatibility surface.
 *
 * GitHub is trusted preset data over the neutral raw-header JSON single-event
 * composer. These exports retain fixture and policy compatibility; request
 * orchestration, failure mapping, test construction, signing policy, and
 * credential validation contain no GitHub-specific branch.
 */

import { webhookRawBodyHmacDeliveryProfilePreset } from './webhook-delivery-engine-presets.js';
import type { WebhookIngressProfileAdapter } from './webhook-profile-runtime.js';
import {
  createRawHeaderJsonSingleEventWebhookCredentialShapeValidator,
  createRawHeaderJsonSingleEventWebhookProfileAdapter,
} from './webhook-raw-header-json-single-event-profile.js';
import {
  webhookCanonicalUuidProfilePreset,
  webhookLowercaseIdentifierEventTypeProfilePreset,
  webhookPositiveDecimalStructuralEvidenceProfilePreset,
} from './webhook-shared-profile-parser-presets.js';

const GITHUB_PROFILE_ID = 'github.webhook.v1' as const;

const delivery = webhookRawBodyHmacDeliveryProfilePreset(GITHUB_PROFILE_ID);
const deliveryId = webhookCanonicalUuidProfilePreset(GITHUB_PROFILE_ID);
const eventType = webhookLowercaseIdentifierEventTypeProfilePreset(
  GITHUB_PROFILE_ID,
);
const structuralEvidence =
  webhookPositiveDecimalStructuralEvidenceProfilePreset(GITHUB_PROFILE_ID);
if (delivery === null
  || delivery.raw_header_metadata === null
  || delivery.delivery_deduplicator === null
  || delivery.metadata_payload_event_normalizer === null
  || delivery.event_projector === null
  || delivery.test_envelope === null
  || deliveryId === null
  || eventType === null
  || structuralEvidence === null) {
  throw new Error('GitHub composed delivery preset is unavailable');
}

export const GITHUB_WEBHOOK_RAW_BODY_HMAC_MECHANISM_PRESET = delivery.mechanism;
export const GITHUB_DELIVERY_ID_PARSER_PRESET = deliveryId.parser;
export const GITHUB_EVENT_TYPE_PARSER_PRESET = eventType.parser;
export const GITHUB_HOOK_ID_PARSER_PRESET = structuralEvidence.parser;
export const GITHUB_RAW_HEADER_METADATA_NORMALIZER_PRESET =
  delivery.raw_header_metadata;
export const GITHUB_NORMALIZED_DELIVERY_DEDUPLICATOR_PRESET =
  delivery.delivery_deduplicator;
export const GITHUB_METADATA_PAYLOAD_EVENT_NORMALIZER_PRESET =
  delivery.metadata_payload_event_normalizer;
export const GITHUB_NORMALIZED_SINGLE_EVENT_PROJECTOR_PRESET =
  delivery.event_projector;
export const GITHUB_RAW_HEADER_JSON_SINGLE_EVENT_TEST_ENVELOPE_PRESET =
  delivery.test_envelope;

const credentialShapeValidator =
  createRawHeaderJsonSingleEventWebhookCredentialShapeValidator(
    GITHUB_PROFILE_ID,
  );

/** Production secrets are generated by Recued. Hidden, extra, inherited,
 * accessor, or non-enumerable fields cannot carry spare authority. */
export const validateGitHubWebhookCredentialShape = (
  credentials: Readonly<Record<string, string>>,
): boolean => credentialShapeValidator(credentials);

const adapter = createRawHeaderJsonSingleEventWebhookProfileAdapter(
  GITHUB_PROFILE_ID,
);

export const createGitHubWebhookProfileAdapter = (
): WebhookIngressProfileAdapter => adapter;
