/** D-158 P2b-ii — the `ask` landing page (the email channel's public
 *  HTTP answer surface).
 *
 *  P2b-i shipped the email channel's two reply paths that exist on every
 *  deployment: the always-present subject-tag reply-by-email path. P2b-ii
 *  adds the path a *public-reachable* server offers in addition — a
 *  one-link `ask` landing page: the emailed ask carries a link, the user
 *  clicks it, picks an option, and submits a form. Structured input
 *  (radio buttons) instead of free-text email parsing.
 *
 *  Notification-native, NOT a D-149 reception endpoint. A D-149
 *  `approval_link` is authored by the user FOR an anonymous third party;
 *  a notification `ask` is generated BY Recued for the user themselves —
 *  a different visitor, authorship, and lifecycle. So the page is backed
 *  by the block's own `PendingAsk` store, not D-149's
 *  `reception_approval_intent`. It REUSES D-149's reception *substrate*
 *  (the server-rendered no-JS form modelled on `approval-link-render.ts`;
 *  the form-nonce CSRF pattern; the reception rate-limiter) — the
 *  render-shape, not the endpoint kind.
 *
 *  Live cross-channel status. Post-D-148 the user's own server renders
 *  this page from its own SQLite — it IS the state authority. An `ask`
 *  answered on Slack / `ui` / by email reply has a non-`open` `PendingAsk`
 *  row; this page reads that same row, so a visit after the answer shows
 *  the honest "already answered" page, not a stale form. No hedge.
 *
 *  Anti-phishing. The page renders the user's `verification_phrase` (the
 *  A.6 `NotificationSettings` field) — a string only the genuine server
 *  knows. A static phishing clone of this page cannot reproduce it, so a
 *  missing / wrong phrase is the user's soft-trust signal. The phrase
 *  rides on the *page*, never in the *email* — an email is forwardable,
 *  so a phrase in the email would leak to a phisher; on the page it is
 *  the page's own un-clonable property.
 *
 *  Capability + CSRF. The unguessable `ask_id` (a 122-bit UUID, emailed
 *  only to the user) in the landing URL is the bearer capability — no
 *  weaker than the always-present reply-by-email path, which anyone with
 *  inbox access could likewise use. The server-issued single-use
 *  `form_nonce` + a same-origin check guard the POST (the D-149 reception
 *  form-nonce pattern). I-9 inbound auth holds the same way it does for
 *  P2a / P2b-i: a reply funnelled to `block.submitAnswer` is trusted
 *  because the inbound path authenticated it — here, the `ask_id`
 *  capability + the CSRF nonce, enforced by the server HTTP route
 *  upstream of `submitAnswer`.
 *
 *  Prefetch-safe. GET renders the form; POST commits. A mail-client link
 *  prefetch issues a GET only, so it can render but never answer — the
 *  D-149 reception GET-renders / POST-commits split.
 *
 *  Leaf posture (mirrors P0 / P1 / P2a / P2b-i): this ships two pure
 *  functions — `renderAskLandingHtml` (the page) and
 *  `parseAskLandingSubmission` (the POST-body decoder) — plus
 *  `ASK_LANDING_RESPONSE_HEADERS`, the security headers the server
 *  response must carry (frame-blocking is header-only, never honoured
 *  from a `<meta>` CSP). The HTTP route that serves them — the GET /
 *  POST handler, the form-nonce store, the rate-limiter, the route
 *  registration, and the `answerLink` builder injected into the email
 *  channel — is the D-158 server-wiring slice (the same deferred slice
 *  that wires P2a's webhook port and P2b-i's `data.mail` watcher). The
 *  server route: GET → `askStore.get` → `renderAskLandingHtml`, set
 *  `ASK_LANDING_RESPONSE_HEADERS`; POST → `parseAskLandingSubmission` →
 *  consume the `form_nonce` → `block.submitAnswer`.
 *
 *  Spec: D-158 § P2 / A.4 / A.6 / N.4 / I-9.
 */

import { htmlEscape, safeHttpUrl } from '../html.js';
import type {
  AskOption,
  ChannelName,
  InboundReply,
  PendingAsk,
} from '../types.js';

/** The channel a landing-page answer is attributed to. The landing page
 *  is the email channel's HTTP answer surface (N.4 — a public-reachable
 *  server's additional email-channel path), so a reply through it counts
 *  as a reply `via` the `email` channel.
 *
 *  ⚠ D-210 audit finding 15 — THAT PREMISE IS NO LONGER TRUE, and the constant
 *  did not follow it. The answer link is now attached to EVERY inline channel
 *  (`index.ts`: `if (deps.askAnswerLink === undefined || channel.capability !==
 *  'inline') return message`), so an approval tapped from a Slack card is
 *  durably recorded as an email reply — on the ask row and in the answer-audit
 *  activity row (`… via ${record.answered_via}`). The attribution is simply
 *  wrong for every non-email inline channel.
 *
 *  ⛔ NOT fixed by swapping the constant. The page cannot know which channel the
 *  reader came from — the URL is identical on all of them — so a truthful value
 *  has to be carried IN the link, which is exactly the per-link attribution
 *  Appendix B already names as an open carry. And a new `ask_landing` channel
 *  name is not a drop-in either: `ChannelName` is a closed set that also drives
 *  readiness probes, the user-togglable `RemoteChannelName` subset, and the
 *  fan-out matrix.
 *
 *  ⏭ The fix is: stamp the originating channel into the answer link at fan-out,
 *  parse it back at the port, and attribute the reply to it — defaulting to
 *  `email` only when absent (an old link). Left NAMED rather than half-done,
 *  because a wrong attribution that looks deliberate is worse than one that is
 *  documented as wrong. ⇒ [[a_reversed_rulings_reasoning_outlives_its_location]] */
const LANDING_REPLY_VIA: ChannelName = 'email';

/** The closed list of form keys the POST decoder accepts — any other key
 *  rejects the submission (`unknown_field`). Defense-in-depth, mirroring
 *  the D-149 reception handlers' `ALLOWED_FORM_KEYS`. */
const ALLOWED_SUBMISSION_KEYS: ReadonlySet<string> = new Set([
  'form_nonce',
  'ask_id',
  'option',
]);

/** D-210 A.8 3d-2c — the namespace every arg-edit field submits under.
 *
 *  The allowlist above stays CLOSED. Edits are admitted by PREFIX instead
 *  of by widening it, so a tampered body still cannot introduce a bare
 *  top-level key, and the decoder never has to know what a valid arg name
 *  is — it hands the server raw `key → string` pairs and the server checks
 *  them against the operation's `ArgEditSchema` allowlist
 *  (`validateEditsAgainstSchema`, which refuses any non-allowlisted key
 *  BEFORE any write). Two layers, each with the knowledge it actually has:
 *  shape here, authority there. */
const EDIT_KEY_PREFIX = 'edit.';

/** Prototype-pollution keys, refused at the decoder as well as at the
 *  server's allowlist. */
const FORBIDDEN_EDIT_KEYS: ReadonlySet<string> = new Set([
  '__proto__',
  'constructor',
  'prototype',
]);

const DEFAULT_OPEN_HEADING = 'Your input is needed';
const ANSWERED_HEADING = 'Already answered';

/** The HTTP response headers the server route serving this page MUST
 *  set on every GET / POST response.
 *
 *  `frame-ancestors` is one of the few CSP directives a browser honours
 *  ONLY from a real response header — it is silently ignored inside a
 *  `<meta http-equiv>` CSP. The page records a user decision on POST, so
 *  clickjacking protection cannot be left to the meta tag; it rides here
 *  as `x-frame-options: DENY` (what D-149's reception `writeHtmlResponse`
 *  also emits). The rest mirror that same reception header set — no
 *  referrer leak, no MIME sniffing, never cached. The meta-tag CSP in
 *  the rendered `<head>` still carries the directives that DO work from
 *  `<meta>` (`default-src` / `style-src` / `form-action` / `base-uri`).
 *
 *  The leaf renders HTML and cannot set headers — the server-wiring
 *  slice spreads this constant onto its response. */
export const ASK_LANDING_RESPONSE_HEADERS: Readonly<Record<string, string>> = {
  'x-frame-options': 'DENY',
  'referrer-policy': 'no-referrer',
  'x-content-type-options': 'nosniff',
  'cache-control': 'no-store',
};

// ── Render input ───────────────────────────────────────────────────

/** One label→value row of the "what will happen" block (D-210 A.8 3d-2b).
 *
 *  PRE-FORMATTED BY THE SERVER, deliberately. The leaf is a renderer: it
 *  escapes and lays out. Deciding what a `datetime` arg reads as (and in
 *  which named zone), what an absent value reads as, and where a long
 *  value is cut are all claims about the held operation — they belong with
 *  the side that can resolve the operation, not in a notification channel.
 *  `value` is therefore display text, already final. */
export interface AskLandingDetail {
  label: string;
  value: string;
  /** D-210 A.8 3d-2c — present ⇒ render an editable control instead of
   *  static text, and the submitted value rides `edit.<key>`.
   *
   *  Fully resolved by the server: which control, what the value attribute
   *  reads, and (for a `datetime-local`) WHICH ZONE that wall clock is in.
   *  The leaf never derives any of it — a control is a promise about what
   *  the submitted value will mean, and only the side that can also PARSE
   *  it back can make that promise. Absent ⇒ the 3d-2b read-only row. */
  edit?: AskLandingEditControl;
}

/** The rendered form control for one editable arg. */
export interface AskLandingEditControl {
  /** Arg key, WITHOUT the `edit.` submission prefix. */
  key: string;
  control: 'text' | 'textarea' | 'number' | 'datetime-local' | 'checkbox';
  /** The `value` attribute. Ignored for `checkbox` (which uses `checked`). */
  value: string;
  checked?: boolean;
  required?: boolean;
  min?: number;
  max?: number;
  pattern?: string;
}

/** What `renderAskLandingHtml` is handed. The `ask` is the block's own
 *  durable `PendingAsk`; `form_nonce` + `action` are server-routing
 *  knowledge the server HTTP route supplies. */
export interface AskLandingRenderInput {
  /** The pending ask to render. `status: 'open'` → the option form;
   *  `answered` / `handled` → the honest "already answered" page. */
  ask: PendingAsk;
  /** The held operation's concrete details — what this approval actually
   *  commits to, rendered above the options so the decision is made with
   *  the values in view rather than from the prose alone.
   *
   *  Absent / empty ⇒ no block (the pre-3d-2b page, byte-identical). That
   *  is the honest state for every ask whose details cannot be resolved:
   *  a non-preflight ask, a batched hold (one ask, N members — no single
   *  set of values to show), an operation whose pack declares no editable
   *  args. Rendered ONLY on the `open` page: once answered the hold is
   *  consumed and there is nothing left to resolve. */
  details?: readonly AskLandingDetail[];
  /** Optional heading for the details block — the held op's human summary
   *  ("Create a booking"). Absent ⇒ a neutral default. */
  details_heading?: string;
  /** D-210 A.8 3d-2c — why the previous submission was refused, re-rendered
   *  above the form so the owner can fix it in place.
   *
   *  A rejected edit that answers only `bad_request` is unusable on a phone:
   *  the page IS the surface, so a refusal it cannot explain is a refusal
   *  the owner cannot act on. */
  details_error?: string;
  /** The user's anti-phishing verification phrase (the A.6
   *  `NotificationSettings` field). Rendered in a recognizable block so
   *  a static phishing clone — which cannot know it — visibly fails the
   *  soft-trust check. Absent → the user set no phrase; no phrase block
   *  is rendered. */
  verification_phrase?: string;
  /** The server-issued single-use CSRF form-nonce — emitted as a hidden
   *  field; the POST route validates it back (the D-149 reception
   *  form-nonce pattern). Used only for an `open` ask; harmlessly
   *  ignored for an already-answered one. */
  form_nonce: string;
  /** The same-origin URL the option `<form>` POSTs to — the server owns
   *  its own routing, so the route supplies this. Used only for an
   *  `open` ask. */
  action: string;
}

/** A decoded landing-page POST. The `reply` is ready for
 *  `block.submitAnswer`; `form_nonce` is surfaced separately for the
 *  server route to validate against its single-use nonce store before
 *  it accepts the reply. */
export interface AskLandingSubmission {
  reply: InboundReply;
  form_nonce: string;
  /** D-210 A.8 3d-2c — raw `edit.<key>` values, prefix stripped, as
   *  SUBMITTED STRINGS. Undefined when the body carried none (the 3d-2b
   *  page, and every non-editable ask).
   *
   *  Deliberately un-coerced and un-validated here: the decoder knows the
   *  body's shape, not the operation's schema. `string` is what an
   *  `application/x-www-form-urlencoded` body actually contains, and
   *  pretending otherwise at this layer would mean guessing a type — and,
   *  for a datetime, a ZONE — that only the server can resolve. */
  edits?: Record<string, string>;
}

// ── Page shell ─────────────────────────────────────────────────────

/** The page CSS — one static inline `<style>` block. Inline because the
 *  leaf cannot reference a server-hosted stylesheet (it does not own a
 *  route); `style-src 'unsafe-inline'` admits exactly this block and
 *  nothing else. Styles only — no script vector. */
const PAGE_STYLE = `*{box-sizing:border-box}
body{margin:0;background:#f4f4f5;color:#18181b;font:16px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif}
.shell{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:24px}
.card{background:#fff;border-radius:14px;box-shadow:0 1px 4px rgba(0,0,0,.1);max-width:480px;width:100%;padding:32px}
.brand{margin:0 0 20px;font-size:13px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#71717a}
.phrase{margin:0 0 6px;padding:12px 16px;background:#fafafa;border:1px solid #e4e4e7;border-left:3px solid #18181b;border-radius:8px}
.phrase-label{display:block;font-size:11px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:#71717a}
.phrase-value{font-size:18px;font-weight:600;word-break:break-word}
.phrase-hint{margin:0 0 24px;font-size:13px;color:#71717a}
h1{margin:0 0 12px;font-size:21px;line-height:1.3}
.prompt{margin:0 0 24px;white-space:pre-wrap;word-break:break-word}
.link{margin:0 0 24px;word-break:break-word}
.details{margin:0 0 24px;padding:4px 16px;background:#fafafa;border:1px solid #e4e4e7;border-radius:9px}
.details dl{margin:0}
.details-legend{display:block;padding:12px 0 4px;font-size:11px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:#71717a}
.detail{display:flex;flex-wrap:wrap;gap:4px 16px;justify-content:space-between;padding:9px 0;border-top:1px solid #ececee}
.detail dt{flex:none;font-size:13px;font-weight:600;color:#71717a;word-break:break-word}
.detail dd{margin:0;flex:1 1 auto;min-width:0;text-align:right;white-space:pre-wrap;word-break:break-word}
.detail--edit{align-items:center}
.detail--edit dd{text-align:left}
.detail input[type=text],.detail input[type=number],.detail input[type=datetime-local],.detail textarea{width:100%;padding:8px 10px;border:1px solid #d4d4d8;border-radius:7px;background:#fff;color:#18181b;font:inherit;font-size:15px}
.detail textarea{resize:vertical;white-space:pre-wrap}
.detail input[type=checkbox]{width:20px;height:20px;margin:0}
.error{margin:0 0 20px;padding:12px 16px;background:#fef2f2;border:1px solid #fecaca;border-left:3px solid #b91c1c;border-radius:8px;color:#7f1d1d}
.notice{margin:0 0 12px}
.recorded{margin:0;padding:12px 16px;background:#fafafa;border:1px solid #e4e4e7;border-radius:8px;color:#3f3f46}
form{margin:0}
fieldset{margin:0 0 20px;padding:0;border:0}
legend{padding:0;margin:0 0 10px;font-size:12px;font-weight:600;letter-spacing:.04em;text-transform:uppercase;color:#71717a}
.option{display:flex;align-items:center;gap:12px;margin:0 0 8px;padding:14px;border:1px solid #e4e4e7;border-radius:9px;cursor:pointer}
.option input{margin:0;flex:none}
button{width:100%;padding:13px;background:#18181b;color:#fff;border:0;border-radius:9px;font-size:16px;font-weight:600;cursor:pointer}
.footer{margin:24px 0 0;font-size:12px;color:#a1a1aa;text-align:center}`;

/** The page head — a strict `<meta>` CSP (no scripts, no remote
 *  resources), `noindex`, and the inline style. The CSP carries only
 *  the directives a browser honours from a `<meta http-equiv>` tag;
 *  frame-blocking (`frame-ancestors` / `X-Frame-Options`) is header-only
 *  — it rides `ASK_LANDING_RESPONSE_HEADERS`, set by the server route.
 *  Modelled on D-149's `renderHead`; self-contained because the leaf
 *  serves no static assets. */
const renderHead = (title: string): string => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'">
<meta name="robots" content="noindex,nofollow">
<title>${htmlEscape(title)}</title>
<style>${PAGE_STYLE}</style>
</head>`;

/** The anti-phishing verification-phrase block. Rendered only when the
 *  user has set a phrase; absent → empty string (no block). */
const renderPhraseBlock = (phrase: string | undefined): string => {
  if (phrase === undefined || phrase.length === 0) return '';
  return `<div class="phrase">
<span class="phrase-label">Your verification phrase</span>
<span class="phrase-value">${htmlEscape(phrase)}</span>
</div>
<p class="phrase-hint">If this is not the phrase you set in Recued, do not respond — close this page.</p>
`;
};

/** Wrap a card body in the full page shell — head, brand mark, the
 *  verification-phrase block, heading, the body inner HTML, footer. */
const renderShell = (input: {
  title: string;
  heading: string;
  phrase: string | undefined;
  inner: string;
}): string => `${renderHead(input.title)}
<body>
<div class="shell">
<div class="card">
<p class="brand">Recued</p>
${renderPhraseBlock(input.phrase)}<h1>${htmlEscape(input.heading)}</h1>
${input.inner}
<div class="footer">A one-time decision delivered by Recued.</div>
</div>
</div>
</body>
</html>
`;

// ── Open page — the option form ────────────────────────────────────

/** One radio row per option. The `value` is the option `id` — the exact
 *  token the POST round-trips and `submitAnswer` re-validates against
 *  the persisted ask; the `label` is what the user reads. */
const renderOptionInputs = (options: readonly AskOption[]): string =>
  options
    .map(
      (option) => `<label class="option">
<input type="radio" name="option" value="${htmlEscape(option.id)}" required>
<span>${htmlEscape(option.label)}</span>
</label>`,
    )
    .join('\n');

const DEFAULT_DETAILS_HEADING = 'What this will do';

/** The "what will happen" block — the held operation's concrete values,
 *  label→value. Read-only in 3d-2b: these are exactly the args the page
 *  will let the owner EDIT in 3d-2c, so showing them first is the
 *  additive half. The empty list renders NOTHING rather than an empty
 *  frame — a block headed "What this will do" listing nothing is a worse
 *  claim than no block at all.
 *
 *  `<dl>` admits only `dt` / `dd` / `div` as children, so the legend sits
 *  outside it in the wrapping `<div class="details">`. */
const numAttr = (name: string, v: number | undefined): string =>
  v === undefined ? '' : ` ${name}="${htmlEscape(String(v))}"`;

/** One editable arg control. Submits under `edit.<key>`.
 *
 *  A `checkbox` carries NO `value` attribute on purpose: an unchecked box
 *  submits nothing at all, so presence-means-true / absence-means-false is
 *  the browser's own semantics, and the server reads it the same way the
 *  webclient inbox and the projection already do. */
const renderEditControl = (edit: AskLandingEditControl): string => {
  const name = htmlEscape(`${EDIT_KEY_PREFIX}${edit.key}`);
  const required = edit.required === true ? ' required' : '';
  if (edit.control === 'checkbox') {
    return `<input type="checkbox" name="${name}" value="on"${
      edit.checked === true ? ' checked' : ''
    }>`;
  }
  if (edit.control === 'textarea') {
    return `<textarea name="${name}"${required} rows="3">${htmlEscape(edit.value)}</textarea>`;
  }
  return `<input type="${htmlEscape(edit.control)}" name="${name}" value="${htmlEscape(
    edit.value,
  )}"${required}${numAttr('min', edit.min)}${numAttr('max', edit.max)}${
    edit.pattern !== undefined ? ` pattern="${htmlEscape(edit.pattern)}"` : ''
  }>`;
};

/** The refusal banner for a submission that came back rejected. */
const renderErrorBlock = (message: string | undefined): string =>
  message === undefined || message.length === 0
    ? ''
    : `\n<p class="error">${htmlEscape(message)}</p>`;

const renderDetailsBlock = (
  details: readonly AskLandingDetail[] | undefined,
  heading: string | undefined,
): string => {
  if (details === undefined || details.length === 0) return '';
  const rows = details
    .map((d) => {
      const cell =
        d.edit !== undefined
          ? renderEditControl(d.edit)
          : htmlEscape(d.value);
      return `<div class="detail${d.edit !== undefined ? ' detail--edit' : ''}">`
        + `<dt>${htmlEscape(d.label)}</dt><dd>${cell}</dd></div>`;
    })
    .join('\n');
  const legend =
    heading !== undefined && heading.length > 0 ? heading : DEFAULT_DETAILS_HEADING;
  return `\n<div class="details">
<span class="details-legend">${htmlEscape(legend)}</span>
<dl>
${rows}
</dl>
</div>`;
};

/** The `open`-ask body — the prompt, the message's optional context
 *  deep link, the held op's details, and a no-JS POST form. The hidden
 *  `form_nonce` (CSRF) + `ask_id` (so the decoder is self-contained,
 *  needing only the body, never the URL) ride as hidden fields. */
const renderOpenBody = (input: AskLandingRenderInput): string => {
  const { ask } = input;
  // The message's optional context deep link — rendered before the form
  // so the decision is made WITH the run / document it references in
  // view. Every other answer surface (`ui`, slack / telegram, the email
  // body) carries `link_url`, so the landing page does too;
  // `safeHttpUrl` gates the scheme before it becomes an `<a href>`.
  const safeLink =
    ask.message.link_url !== undefined
      ? safeHttpUrl(ask.message.link_url)
      : null;
  const linkLine =
    safeLink !== null
      ? `\n<p class="link"><a href="${htmlEscape(safeLink)}">${htmlEscape(safeLink)}</a></p>`
      : '';
  // ⚠ The details block sits INSIDE the form. Once a row can be an
  // `<input>` (3d-2c), a block rendered outside the form is a set of
  // controls the browser never submits — the owner would edit the slot,
  // approve, and the original value would be what lands. Read-only rows are
  // inert inside a form, so both shapes take the same position rather than
  // the position depending on a property of the rows.
  const detailsBlock = renderDetailsBlock(input.details, input.details_heading);
  return `<p class="prompt">${htmlEscape(ask.message.text)}</p>${linkLine}${renderErrorBlock(
    input.details_error,
  )}
<form method="POST" action="${htmlEscape(input.action)}">
<input type="hidden" name="form_nonce" value="${htmlEscape(input.form_nonce)}">
<input type="hidden" name="ask_id" value="${htmlEscape(ask.ask_id)}">${detailsBlock}
<fieldset>
<legend>Choose one</legend>
${renderOptionInputs(ask.options)}
</fieldset>
<button type="submit">Submit response</button>
</form>`;
};

// ── Answered page — honest cross-channel status ────────────────────

/** The label the user chose, resolved from the recorded answer's option
 *  id. Falls back to the raw id when the option is gone from the ask
 *  (mirrors D-149's `describeApprovalOutcome` fallback). */
const answeredOptionLabel = (ask: PendingAsk): string | null => {
  if (ask.answer === undefined) return null;
  const chosen = ask.options.find((o) => o.id === ask.answer?.option);
  return chosen !== undefined ? chosen.label : ask.answer.option;
};

/** The non-`open` body — the honest "already answered" page. Reached
 *  whatever channel the answer arrived on (the `PendingAsk` row is the
 *  shared cross-channel truth), so no hedge: it states the ask is done
 *  and, when an answer is recorded, echoes the chosen option. */
const renderAnsweredBody = (ask: PendingAsk): string => {
  const label = answeredOptionLabel(ask);
  const recorded =
    label !== null
      ? `\n<p class="recorded">Response recorded: ${htmlEscape(label)}</p>`
      : '';
  return `<p class="notice">This decision has already been answered — there is nothing for you to do here.</p>${recorded}`;
};

// ── Public surface ─────────────────────────────────────────────────

/** Render the `ask` landing page. Pure — given the same input it emits
 *  the same HTML. Dispatches on `ask.status`: `open` → the option form
 *  (uses `form_nonce` + `action`); `answered` / `handled` → the honest
 *  "already answered" page. */
export const renderAskLandingHtml = (
  input: AskLandingRenderInput,
): string => {
  const { ask } = input;
  if (ask.status === 'open') {
    return renderShell({
      title: ask.message.title ?? DEFAULT_OPEN_HEADING,
      heading: ask.message.title ?? DEFAULT_OPEN_HEADING,
      phrase: input.verification_phrase,
      inner: renderOpenBody(input),
    });
  }
  return renderShell({
    title: ANSWERED_HEADING,
    heading: ANSWERED_HEADING,
    phrase: input.verification_phrase,
    inner: renderAnsweredBody(ask),
  });
};

/** Decode an `application/x-www-form-urlencoded` landing-page POST body
 *  into an `AskLandingSubmission`, or an `{ error }` when it is not a
 *  usable submission. Pure + self-contained — every field the server
 *  route needs (`ask_id`, the chosen `option`, the `form_nonce`) rides
 *  in the body as a hidden / radio field, so the decoder never needs the
 *  request URL.
 *
 *  `unknown_field` — the body carried a key outside the closed list (a
 *  tampered or malformed submission). `malformed` — a required field is
 *  missing or empty. The chosen `option` is NOT validated against any
 *  ask here: `block.submitAnswer` re-validates it (and dedups) against
 *  the persisted `PendingAsk`. */
export const parseAskLandingSubmission = (
  rawBody: string,
): AskLandingSubmission | { error: 'unknown_field' | 'malformed' } => {
  const params = new URLSearchParams(rawBody);
  const edits: Record<string, string> = {};
  let sawEdit = false;
  for (const [key, value] of params) {
    if (ALLOWED_SUBMISSION_KEYS.has(key)) continue;
    if (!key.startsWith(EDIT_KEY_PREFIX)) return { error: 'unknown_field' };
    const argKey = key.slice(EDIT_KEY_PREFIX.length);
    // A bare `edit.` names nothing, and `__proto__` / `constructor` /
    // `prototype` are refused here as well as at the allowlist — the
    // decoder builds a plain object and must not be the layer that hands
    // one a poisoned key. (`validateEditsAgainstSchema` refuses them too;
    // this is the defense-in-depth half.)
    if (argKey.length === 0 || FORBIDDEN_EDIT_KEYS.has(argKey)) {
      return { error: 'unknown_field' };
    }
    // A repeated key is a tampered / malformed body, not a last-wins
    // convenience: silently keeping one of two conflicting values for the
    // SAME arg is exactly the kind of quiet choice an approval must not make.
    if (Object.hasOwn(edits, argKey)) return { error: 'unknown_field' };
    edits[argKey] = value;
    sawEdit = true;
  }
  const ask_id = (params.get('ask_id') ?? '').trim();
  const option = (params.get('option') ?? '').trim();
  const form_nonce = (params.get('form_nonce') ?? '').trim();
  if (
    ask_id.length === 0 ||
    option.length === 0 ||
    form_nonce.length === 0
  ) {
    return { error: 'malformed' };
  }
  return {
    reply: { ask_id, option, via: LANDING_REPLY_VIA },
    form_nonce,
    ...(sawEdit ? { edits } : {}),
  };
};
