/** D-158 P2 — the transport-backed remote `Channel` (slack / telegram).
 *
 *  Slack and Telegram are structurally one channel — both wrap a
 *  `@recued/transport` `Transport` and differ only in which vendor
 *  transport is injected. `createRemoteChannel` is that one adapter; the
 *  channel's `name` is the transport's `vendor`. (The spec's A.1 sketch
 *  lists `channels/slack.ts` + `channels/telegram.ts`; one factory keyed
 *  on `transport.vendor` is the DRY realization — the two adapters would
 *  be byte-identical but for that one value.)
 *
 *  Outbound: `deliverNotify` → `transport.send`; `deliverAsk` →
 *  `transport.sendPrompt` (interactive option buttons — the `ask_id`
 *  rides as the prompt `correlation_id`); `closeAsk` →
 *  `transport.closePrompt` (best-effort — strips a still-open prompt's
 *  buttons).
 *  Inbound: `parseInboundReply` decodes an already-authenticated vendor
 *  callback payload into an `InboundReply` for the block's `submitAnswer`.
 *
 *  Leaf posture (mirrors P0 / P1): the block is a leaf and cannot reach
 *  the connection store or the D-148 P9 webhook port. The BYO credential
 *  is an injected `CredentialResolver` seam; inbound *authentication* is
 *  the server's webhook port (D-148 P9 `verifySignature`), upstream of
 *  `parseInboundReply` — this adapter only ever parses an already-
 *  verified payload (the I-9 contract: an `InboundReply` is trusted,
 *  authentication is the inbound path's responsibility — see types.ts).
 *
 *  P2a limitation (→ D-158 P3 hardening): the `ask_id → vendor message`
 *  map is in-memory and process-scoped. Within a process it makes
 *  `deliverAsk` idempotent (a re-delivery is a no-op, not a second
 *  message) and lets `closeAsk` strip the buttons. Across a restart the
 *  map is empty: the boot re-delivery sweep re-posts the prompt, and
 *  `closeAsk` no-ops. Both are harmless — the block's first-answer-wins
 *  dedup makes a stale button safe — but persisting the vendor message
 *  id is D-158 P3.
 *
 *  Spec: D-158 § P2 / A.4 / I-9.
 */

import type {
  InteractiveTransport,
  Transport,
  ParsedInbound,
  TransportSendResult,
} from '@recued/transport';
import type { Channel, ChannelCapability } from './channel.js';
import { matchTextAnswer, renderAnswerHint } from '../ask-text-answer.js';
import type {
  ChannelName,
  InboundReply,
  NotificationMessage,
} from '../types.js';
import { isChannelName, type AskOption } from '../types.js';

/** The BYO credential a remote channel sends with — resolved fresh per
 *  delivery from `connection.notification` (D-125). */
export interface RemoteChannelCredential {
  /** The send token, already decrypted — resolved through the messenger
   *  send-credential seam (`resolveMessengerSendToken`), never read off a raw
   *  `auth.token` field. */
  token: string;
  /** The vendor-surface destination — a Slack channel id, a Telegram
   *  chat id. */
  recipient: string;
  /** D-238 — the ONLY sender whose typed reply may settle an ask here: the
   *  enrolled principal, i.e. the owner.
   *
   *  ⛔⛔ **A bound chat is not an authorization boundary.** The Teams recipient
   *  is a chat id, and a chat can have other people in it. Without this, an exact
   *  answer from ANY participant settles the owner's approval — a colleague
   *  typing `Approve` in a group thread authorizes a side effect on the owner's
   *  data. The ask is generated BY Recued FOR the owner (contrast a D-149
   *  `approval_link`, which is authored by the owner FOR a third party), so
   *  approval authority is the owner's alone.
   *
   *  ⚠ Absent ⇒ typed answers are REFUSED, not waved through. "We do not know
   *  who may approve" must never resolve to "anyone may". */
  expected_sender?: string;
}

/** Resolves the remote channel's current `connection.notification`
 *  credential, or `null` when none is enrolled (the channel was
 *  enabled, then its credential later deleted). Injected — the block is
 *  a leaf and cannot reach the connection store. */
export type CredentialResolver = () => Promise<RemoteChannelCredential | null>;

/** A remote `Channel` plus its inbound parsers. The block consumes the
 *  `Channel` surface; the server's webhook port uses
 *  `parseInboundReply` to funnel an authenticated vendor callback into
 *  `block.submitAnswer`, and `parseInboundMessage` to surface a regular
 *  user message (the WatchSource messenger push source). */
export interface RemoteChannel extends Channel {
  /** Decode an already-authenticated (I-9) inbound vendor callback
   *  payload into an `InboundReply`, or `null` when the payload is not
   *  a recognizable option selection. */
  parseInboundReply(payload: unknown): InboundReply | null;
  /** Decode an already-authenticated (I-9) inbound vendor payload into
   *  a plain user message, or `null` for anything that is not one
   *  (control events, bot echoes, button presses — the vendor payload
   *  shapes are disjoint from `parseInboundReply`'s, but call this on
   *  the reply-null fall-through anyway so a press is never
   *  double-classified). Delegates to `transport.parseInbound`. */
  parseInboundMessage(payload: unknown): ParsedInbound | null;
}

export interface RemoteChannelDeps {
  /** The vendor transport. `InteractiveTransport` for an `inline` channel —
   *  it must render buttons and decode the press. A non-`inline` channel may
   *  supply the base `Transport`, which is the whole point of D-238 § 2: a
   *  vendor whose ingress cannot carry a button press has no `sendPrompt` to
   *  give. The channel's `name` is the transport's `vendor`. */
  transport: InteractiveTransport | Transport;
  /** Resolves the BYO `connection.notification` credential, per call. */
  resolveCredential: CredentialResolver;
  /** D-238 § 2 — HOW an ask renders here. Defaults to `'inline'`, which is what
   *  every vendor shipping before Teams declares, so existing callers are
   *  unchanged. Must match the vendor declaration's `capability`; the D-163
   *  ratchet asserts the table and the adapter agree. */
  capability?: ChannelCapability;
  /** D-238 — the `/ask/<ask_id>` builder, for a channel that answers by LINK
   *  rather than by button.
   *
   *  A `landing-page` channel composes its own affordance: `withAnswerLink`
   *  (`index.ts`) deliberately appends only for `inline` channels, so without
   *  this the ask would arrive with no way to answer it. Absent is the honest
   *  state on a non-public deployment — the resolver refuses a private hostname
   *  by design — and the ask then carries the typed-reply hint alone. */
  answerLink?: (ask_id: string, via?: string) => string;
}

/** Narrow at the one place it matters. A channel built `inline` MUST have the
 *  interactive superset — the alternative is discovering it at the first ask,
 *  on a best-effort path that swallows the error. */
const isInteractive = (t: InteractiveTransport | Transport): t is InteractiveTransport =>
  typeof (t as InteractiveTransport).sendPrompt === 'function';

/** The text a closed (button-stripped) prompt is left showing — the
 *  original message, with the title inlined since the option buttons
 *  that carried the visual structure are gone. */
const composeCloseText = (message: NotificationMessage): string =>
  message.title !== undefined
    ? `${message.title}\n\n${message.text}`
    : message.text;

/** Create a transport-backed remote channel. */
export const createRemoteChannel = (
  deps: RemoteChannelDeps,
): RemoteChannel => {
  const { transport, resolveCredential } = deps;
  const capability: ChannelCapability = deps.capability ?? 'inline';
  // ⛔ An `inline` channel with a non-interactive transport would construct
  // cleanly, notify fine, and then throw on the FIRST ASK — on the block's
  // best-effort fan-out, which catches. The owner would see a channel that
  // delivers notifications and silently never delivers an approval. Fail at
  // construction, where it is answerable.
  if (capability === 'inline' && !isInteractive(transport)) {
    throw new Error(
      `createRemoteChannel: '${transport.vendor}' declares capability 'inline' but its `
      + 'transport has no sendPrompt — an inline channel must render and resolve '
      + 'option buttons. Declare a non-inline capability, or supply an '
      + 'InteractiveTransport.',
    );
  }
  // D-192 CORE #6 — `Transport.vendor` widened to an open slug; a transport-
  // backed remote channel's name IS its vendor and must be a registered
  // notification `ChannelName`. Fail loud if a transport is wired whose vendor
  // isn't a known channel (seam 10).
  // ⛔ NOT "must be added to CHANNEL_NAMES first" — that read as an instruction
  // to edit a list, and the list is DERIVED: `NOTIFICATION_CHANNEL_NAMES`
  // splices `...MESSENGER_VENDOR_SLUGS`, so declaring the vendor in contracts
  // is what makes it a channel. See `messenger-vendors.ts` § ADDING A VENDOR.
  if (!isChannelName(transport.vendor)) {
    throw new Error(
      `createRemoteChannel: transport vendor '${transport.vendor}' is not a registered notification channel`,
    );
  }
  const name: ChannelName = transport.vendor;

  /** ask_id → what `closeAsk` needs to strip a delivered prompt's
   *  buttons. In-memory, process-scoped (see the file header for the
   *  restart limitation). */
  const delivered = new Map<
    string,
    {
      vendor_message_id: string;
      close_text: string;
      /** D-238 — what a TYPED reply is matched against. Held per ask because
       *  the matcher must never see options from an ask this channel did not
       *  deliver. */
      options: readonly AskOption[];
      /** Answered or closed elsewhere. ⛔ Kept rather than deleting the entry:
       *  the delivery record still suppresses a re-delivery, but a late typed
       *  reply must NOT answer a settled ask. */
      closed: boolean;
      /** D-238 — who may answer this by typing. Captured from the credential in
       *  force WHEN THE ASK WENT OUT, because `parseInboundReply` is sync and
       *  cannot resolve one. Undefined ⇒ typed answers refused for this ask. */
      expected_sender: string | undefined;
    }
  >();

  const credentialOrThrow = async (
    op: string,
  ): Promise<RemoteChannelCredential> => {
    const credential = await resolveCredential();
    if (credential === null) {
      throw new Error(
        `${name} channel: ${op} — no connection.notification credential enrolled`,
      );
    }
    return credential;
  };

  /** A `Channel` signals a failed delivery by throwing — the block's
   *  fan-out / notify paths are best-effort and catch. Bridge the
   *  transport's discriminated `{ ok: false }` to that contract. */
  const throwOnFailure = (result: TransportSendResult, op: string): void => {
    if (!result.ok) {
      throw new Error(
        `${name} channel: ${op} — ${result.error.kind}: ${result.error.detail}`,
      );
    }
  };

  return {
    name,
    capability,
    // D-163 amendment / D-167 § "Channel ownership signal" — Slack /
    // Telegram are external apps that own downstream presentation;
    // Recued has no restore-on-display hook, so it does not own the
    // LLM↔user boundary here.
    owns_llm_egress: false,

    async deliverNotify(message) {
      const { token, recipient } = await credentialOrThrow('deliverNotify');
      const result = await transport.send({
        recipient,
        token,
        text: message.text,
        ...(message.title !== undefined ? { title: message.title } : {}),
        ...(message.link_url !== undefined ? { link_url: message.link_url } : {}),
      });
      throwOnFailure(result, 'deliverNotify');
    },

    async deliverAsk(ask_id, message, options) {
      // Within-process idempotency — the boot re-delivery sweep, or any
      // double call, must not post a second prompt for an ask already
      // delivered this process.
      if (delivered.has(ask_id)) return;

      // D-163 N.3 / I-2 — the block MUST NOT route an ask here when the channel
      // is not ask-capable, so reaching this on a non-`inline` channel means a
      // routing bug upstream. The `Channel.deliverAsk` contract is explicit
      // about the response: fall back to a passive notify body, NEVER silently
      // strand the ask. Throwing would strand it (the fan-out catches), and
      // returning would strand it more quietly still.
      if (!isInteractive(transport)) {
        const credential = await credentialOrThrow('deliverAsk');
        const { token, recipient } = credential;
        // BOTH answer paths in one body: the link for anyone who can reach it,
        // and the option list so the owner can simply type one back. Neither is
        // a fallback for the other — a public deployment gets a structured form,
        // an office LAN gets a typed reply, and most owners will use whichever
        // is fewer taps from where they are standing.
        // ⛔ From the matcher's own module, so what is SHOWN and what is
        // ACCEPTED cannot drift. Hand-rolling this line is how the prompt came
        // to advertise bare labels while the matcher also took positions and
        // internal ids.
        const hint = renderAnswerHint(options);
        // ⛔ Pass THIS channel's name. The landing page attributes the answer
        // to whatever rides here, and omitting it means every Teams approval is
        // durably audited as an email reply.
        const link = deps.answerLink?.(ask_id, name);
        const body = [composeCloseText(message), hint, link]
          .filter((part) => part !== undefined && part.length > 0)
          .join('\n\n');

        const result = await transport.send({ recipient, token, text: body });
        throwOnFailure(result, 'deliverAsk');
        // No vendor message id: there are no buttons to strip, so `closeAsk`
        // correctly no-ops on the prompt itself.
        delivered.set(ask_id, {
          vendor_message_id: '',
          close_text: composeCloseText(message),
          options,
          closed: false,
          expected_sender: credential.expected_sender,
        });
        return;
      }
      const { token, recipient } = await credentialOrThrow('deliverAsk');
      const result = await transport.sendPrompt({
        recipient,
        token,
        text: message.text,
        ...(message.title !== undefined ? { title: message.title } : {}),
        // The ask_id IS the transport correlation token — it round-
        // trips through the vendor callback and comes back on the press.
        correlation_id: ask_id,
        options: options.map((option) => ({
          id: option.id,
          label: option.label,
        })),
      });
      throwOnFailure(result, 'deliverAsk');
      // result.ok holds past throwOnFailure. Record the vendor message
      // id for closeAsk; a success that omits the id leaves the prompt
      // uncloseable — stored as '' so a re-delivery is still suppressed
      // and closeAsk no-ops on it.
      delivered.set(ask_id, {
        vendor_message_id:
          result.ok && result.vendor_message_id !== undefined
            ? result.vendor_message_id
            : '',
        close_text: composeCloseText(message),
        options,
        closed: false,
        // Unused on an interactive channel: a button press is authenticated by
        // the vendor's own callback, not by matching a sender.
        expected_sender: undefined,
      });
    },

    async closeAsk(ask_id) {
      const entry = delivered.get(ask_id);
      // ⛔ Mark settled BEFORE the early returns below. Those exist for a prompt
      // with no buttons to strip — exactly the non-interactive case — so leaving
      // the flag until after them would let a typed reply answer an ask that was
      // already decided somewhere else. First-answer-wins is enforced upstream
      // too, but a channel that keeps offering a settled question is its own bug.
      if (entry !== undefined) entry.closed = true;
      // Unknown ask — never delivered this process, or delivered before
      // a restart — or delivered with no vendor message id: a no-op,
      // per the `Channel.closeAsk` contract.
      if (entry === undefined || entry.vendor_message_id === '') return;
      // Best-effort throughout — a credential that has since vanished,
      // or a failed close, leaves a stale (but, per the block's first-
      // answer-wins dedup, harmless) button; `closeAsk` never throws.
      const credential = await resolveCredential();
      if (credential === null) return;
      // Unreachable for a non-interactive transport — its `deliverAsk` records
      // an empty vendor_message_id, which returned above — but narrowed rather
      // than asserted, because a cast here would be load-bearing on that.
      if (!isInteractive(transport)) return;
      await transport.closePrompt({
        recipient: credential.recipient,
        token: credential.token,
        vendor_message_id: entry.vendor_message_id,
        text: entry.close_text,
      });
    },

    parseInboundReply(payload) {
      // D-238 — a channel with no buttons answers by TYPING. The matcher is
      // deliberately strict (exact option, alone, one open ask); everything else
      // is ordinary conversation and returns null so it passes through.
      //
      // ⛔ Scoped to the asks THIS channel delivered and has not closed. A wider
      // set would let a reply in one conversation answer an ask the owner saw in
      // another, and a settled ask would stay answerable after the fact.
      if (!isInteractive(transport)) {
        const parsed = transport.parseInbound(payload);
        if (parsed === null) return null;
        // ⛔⛔ AUTHORITY, before matching. A bound chat can have other people in
        // it, and an exact `Approve` from a colleague would otherwise settle the
        // owner's approval. Only asks whose approver we can CONFIRM is this
        // sender are considered — an ask with no known approver drops out of the
        // open set entirely, so "we do not know who may approve" resolves to
        // "nobody may", never to "anyone may".
        const sender = parsed.from.trim();
        const open = [...delivered.entries()]
          .filter(([, entry]) => !entry.closed)
          .filter(([, entry]) =>
            entry.expected_sender !== undefined
            && entry.expected_sender.length > 0
            && entry.expected_sender === sender)
          .map(([ask_id, entry]) => ({ ask_id, options: entry.options }));
        const outcome = matchTextAnswer(parsed.text, open);
        if (outcome.kind !== 'answer') return null;
        return { ask_id: outcome.ask_id, option: outcome.option, via: name };
      }
      const choice = transport.parseInboundChoice(payload);
      if (choice === null) return null;
      // correlation_id IS the ask_id (deliverAsk set it); option_id IS
      // the chosen AskOption.id. The block's `submitAnswer` re-validates
      // the option against the persisted ask and dedups.
      return {
        ask_id: choice.correlation_id,
        option: choice.option_id,
        via: name,
      };
    },

    parseInboundMessage(payload) {
      return transport.parseInbound(payload);
    },
  };
};
