/** AAD v1 → v2: the migration, driven against a REAL v1-sealed record.
 *
 *  ⛔⛔ THE FIXTURE WAS PRODUCED BY THE v1 CODE, BEFORE v2 EXISTED.
 *  `__fixtures__/token-aad-v1-record.json` was generated by running the
 *  then-current `createWebclientTokenStore().wrap()` — the real wrap path, real
 *  AES-GCM, fixed key and IV — and committed. It is an artefact, not a fixture
 *  someone wrote to match the reader.
 *
 *  🔑 THAT DISTINCTION IS THE WHOLE POINT. A hand-built "v1 record" that the v2
 *  reader happens to accept proves the fixture, not the migration — and the
 *  failure mode of getting this wrong is EVERY USER RE-PAIRS. The bytes below
 *  cannot be adjusted to make a broken fallback pass; they either open or they
 *  do not.
 *
 *  ⚠ If the AAD canonicalisation ever changes shape again, this file is how you
 *  find out you broke everyone's stored bearer.
 */
import { readFileSync } from 'node:fs';
import { codeOf } from '../__tests__/helpers/source-text.js';
import { resolve } from 'node:path';
import { webcrypto } from 'node:crypto';
import { describe, expect, it, vi } from 'vitest';
import type { WebclientTokenRecord } from '@recued/contracts';

import {
  createWebclientTokenStore,
  WebclientTokenCorruptError,
  type WebclientTokenAad,
} from './token-store.js';

/** ⚠ A LOCAL SHAPE FOR THE THREE CALLS THIS FILE MAKES, and the reason is the
 *  same one `port-mapping-supervisor.ts` gives for not naming a timer handle:
 *  node's `NodeJS.BufferSource` and the DOM's `BufferSource` are different
 *  nominal types, so writing either one drags this file's compilability into
 *  whichever lib set the consuming tsconfig happens to pull in. The bytes are
 *  identical; only the declarations disagree. One cast at the boundary beats a
 *  cast per argument. */
interface MinimalSubtle {
  importKey(
    format: 'raw', key: Uint8Array, algo: string, extractable: boolean, usages: string[],
  ): Promise<unknown>;
  encrypt(
    algo: { name: string; iv: Uint8Array; additionalData?: Uint8Array },
    key: unknown, data: Uint8Array,
  ): Promise<ArrayBuffer>;
  decrypt(
    algo: { name: string; iv: Uint8Array; additionalData?: Uint8Array },
    key: unknown, data: Uint8Array,
  ): Promise<ArrayBuffer>;
}
const subtle = webcrypto.subtle as unknown as MinimalSubtle;

/** The exact key + IV the fixture was sealed with. */
const KEY_BYTES = new Uint8Array(32);
for (let i = 0; i < 32; i++) KEY_BYTES[i] = (i * 7) % 256;
const IV = new Uint8Array(12);
for (let i = 0; i < 12; i++) IV[i] = 200 - i;

/** The pair context the fixture was sealed under. */
const V1_AAD: WebclientTokenAad = {
  token_id: 'tok_v1_fixture',
  server_url: 'wss://alice.recued.net/ws',
  server_public_key: 'ed25519:AAAAC3NzaC1lZDI1NTE5AAAAIFIXTUREKEYFORTESTONLY',
};
const V1_BEARER = 'bearer-sealed-under-aad-v1';

const v1Record = (): WebclientTokenRecord =>
  JSON.parse(readFileSync(
    resolve(import.meta.dirname, '__fixtures__', 'token-aad-v1-record.json'),
    'utf-8',
  )) as WebclientTokenRecord;

const realCrypto = async (onLegacyAadRecord?: (r: WebclientTokenRecord, a: WebclientTokenAad) => void) => {
  const key = await subtle.importKey('raw', KEY_BYTES, 'AES-GCM', false, ['encrypt', 'decrypt']);
  return createWebclientTokenStore({
    resolveKey: async () => key,
    encrypt: async ({ key: k, iv, plaintext, additional_data }) =>
      new Uint8Array(await subtle.encrypt(
        { name: 'AES-GCM', iv, additionalData: additional_data }, k, plaintext)),
    decrypt: async ({ key: k, iv, ciphertext, additional_data }) =>
      new Uint8Array(await subtle.decrypt(
        { name: 'AES-GCM', iv, additionalData: additional_data }, k, ciphertext)),
    randomBytes: () => IV,
    now: () => 1_700_000_000_000,
    ...(onLegacyAadRecord !== undefined ? { onLegacyAadRecord } : {}),
  });
};

describe('AAD v1 → v2 migration', () => {
  it('⛔⛔ OPENS A REAL v1-SEALED RECORD — nobody re-pairs', async () => {
    // The assertion the whole change rests on. If this fails, shipping v2
    // forces every existing install to re-pair every device.
    const store = await realCrypto();
    expect(await store.unwrap(v1Record(), V1_AAD)).toBe(V1_BEARER);
  });

  it('⛔ and SIGNALS that the record is stale, so the migration converges', async () => {
    // Without the signal a v1 record reads fine for ever, the population never
    // drains, and v1 support can never be retired — a second format, permanently.
    const seen: WebclientTokenRecord[] = [];
    const store = await realCrypto((r) => { seen.push(r); });
    await store.unwrap(v1Record(), V1_AAD);
    expect(seen).toHaveLength(1);
    expect(seen[0]?.token_id).toBe('tok_v1_fixture');
  });

  it('⛔⛔ RE-SEALING PRODUCES A RECORD THAT NO LONGER NEEDS THE URL', async () => {
    // The end state: after one re-wrap, the same bearer opens with the URL gone
    // from the AAD entirely — which is what makes the address editable.
    const store = await realCrypto();
    const bearer = await store.unwrap(v1Record(), V1_AAD);
    const resealed = await store.wrap({
      token_id: V1_AAD.token_id, bearer, aad: V1_AAD,
    });
    const urlless: WebclientTokenAad = {
      token_id: V1_AAD.token_id,
      server_public_key: V1_AAD.server_public_key,
    };
    expect(await store.unwrap(resealed, urlless)).toBe(bearer);
  });

  it('⛔⛔ A RE-SEALED RECORD SURVIVES THE URL CHANGING — the entire point', async () => {
    // A self-hoster moves `public_port` off 443. Under v1 the stored bearer was
    // invalidated by that move ("a re-pair, not an edit"); under v2 it opens.
    const store = await realCrypto();
    const bearer = await store.unwrap(v1Record(), V1_AAD);
    const resealed = await store.wrap({ token_id: V1_AAD.token_id, bearer, aad: V1_AAD });
    expect(await store.unwrap(resealed, {
      ...V1_AAD,
      server_url: 'wss://alice.recued.net:4433/ws',   // the port moved
    })).toBe(bearer);
  });

  it('⛔ a DIFFERENT SERVER IDENTITY still fails, at both versions', async () => {
    // Isolation is preserved, not relaxed: the key is what binds now, so a
    // record lifted toward another server's identity must not open.
    const store = await realCrypto();
    const wrongKey: WebclientTokenAad = { ...V1_AAD, server_public_key: 'ed25519:SOMEONEELSE' };
    await expect(store.unwrap(v1Record(), wrongKey)).rejects.toThrow(WebclientTokenCorruptError);
  });

  it('⛔ a DIFFERENT token_id still fails — profile isolation intact', async () => {
    const store = await realCrypto();
    const lifted = { ...v1Record(), token_id: 'tok_other' };
    await expect(store.unwrap(lifted, { ...V1_AAD, token_id: 'tok_other' }))
      .rejects.toThrow(WebclientTokenCorruptError);
  });

  it('⚠ a v2 record with NO url does not attempt the v1 fallback', async () => {
    // A v2-sealed record that fails to open is corrupt. Retrying it under a v1
    // AAD built from an absent `server_url` would turn one clean failure into a
    // second, more confusing one.
    const store = await realCrypto();
    const corrupt = { ...v1Record(), ciphertext_b64: v1Record().ciphertext_b64.replace(/^.{4}/, 'AAAA') };
    await expect(store.unwrap(corrupt, {
      token_id: V1_AAD.token_id,
      server_public_key: V1_AAD.server_public_key,
    })).rejects.toThrow(WebclientTokenCorruptError);
  });

  it('⚠ the legacy signal does NOT fire for a v2 record', async () => {
    // A false signal would make the caller re-seal on every read for ever.
    const seen: WebclientTokenRecord[] = [];
    const store = await realCrypto((r) => { seen.push(r); });
    const fresh = await store.wrap({
      token_id: 'tok_fresh', bearer: 'b', aad: { token_id: 'tok_fresh', server_public_key: 'k' },
    });
    await store.unwrap(fresh, { token_id: 'tok_fresh', server_public_key: 'k' });
    expect(seen).toHaveLength(0);
  });

  it('⚠ a throwing legacy signal does not fail the unwrap', async () => {
    // It runs inside the read path; a failing re-seal must not cost the user
    // their session.
    const store = await realCrypto(() => { throw new Error('persist failed'); });
    expect(await store.unwrap(v1Record(), V1_AAD)).toBe(V1_BEARER);
  });

  // ── The domain tag (found by mutation) ──────────────────────────────────

  it('⚠ the two AAD formats carry DIFFERENT domain tags — structural, and here is why', () => {
    // ⛔ MUTATION FOUND THIS UNTESTABLE FROM OUTSIDE, WHICH IS ITSELF THE
    // FINDING. Changing v2's domain string to v1's reds NOTHING: both ends call
    // the same private builder, so any string works as long as the two builders
    // disagree — and today they also disagree by FIELD SET (`server_url`), so
    // the tag is carrying no weight it can be observed to carry.
    //
    // 🔑 That is exactly the accident recorded for `server_identity_key`'s five
    // protocols: formats staying apart because their key sets happen to differ
    // is not a rule, and the failure when it stops being true is a silent
    // cross-format unwrap rather than a red test. A v3 with v2's field set
    // would have ONLY the tag to separate it.
    //
    // So this is pinned at the source, and says so rather than pretending to be
    // a behavioural test.
    const source = readFileSync(
      resolve(import.meta.dirname, 'token-store.ts'),
      'utf-8',
    );
    const domains = [...source.matchAll(/domain: '(recued\.webclient\.token\.aad\.[^']+)'/g)]
      .map((m) => m[1]!);
    expect(domains.length).toBeGreaterThanOrEqual(2);
    expect(new Set(domains).size, `two AAD formats share a domain tag: ${domains.join(', ')}`)
      .toBe(domains.length);
  });

  it('⛔ a v2-sealed record cannot be opened as v1, whatever the URL', async () => {
    // The observable half: v2 drops `server_url`, so its bytes can never match
    // a v1 AAD built over the same record. Sealing fresh and probing with a
    // v1-shaped AAD proves the formats do not silently interchange.
    const store = await realCrypto();
    const v2 = await store.wrap({
      token_id: 'tok_v2',
      bearer: 'fresh-bearer',
      aad: { token_id: 'tok_v2', server_public_key: V1_AAD.server_public_key },
    });
    // With a server_url present the reader tries v2 FIRST and succeeds — the
    // URL is simply ignored, which is the whole point of the migration.
    await expect(store.unwrap(v2, {
      token_id: 'tok_v2',
      server_url: 'wss://somewhere.else/ws',
      server_public_key: V1_AAD.server_public_key,
    })).resolves.toBe('fresh-bearer');
    // …and it is NOT because the v1 path opened it: a wrong KEY still fails,
    // so the success above was a real v2 verify rather than a lenient fallback.
    await expect(store.unwrap(v2, {
      token_id: 'tok_v2',
      server_url: 'wss://somewhere.else/ws',
      server_public_key: 'a-different-key',
    })).rejects.toThrow();
  });

  // ── The retirement ratchet ──────────────────────────────────────────────

  it('⛔⛔ v1 support may not be deleted in a surface where nothing re-seals', async () => {
    // ⛔ THE COMMENT THAT USED TO GOVERN THIS WAS FALSE AND DESTRUCTIVE: "every
    // unwrap re-seals, so the population drains on its own" invited deleting
    // the only reader of every un-migrated record. A corrected comment is
    // exactly what failed, so this is a ratchet.
    //
    // ⚠ PER SURFACE, NOT GLOBAL. The webclient drains (webclient-main.ts wires
    // `onLegacyAadRecord` to a re-seal); the bridge does not, and a single
    // global flag would have relaxed the bridge's guard on the webclient's
    // work. A first version did exactly that.
    //
    // ⚠ AND IT READS CODE, NOT PROSE. An earlier version used `.includes(...)`
    // on raw text and decided the hook was WIRED because another file MENTIONED
    // it in a comment saying it was not — leaving the ratchet inert while
    // passing. It also missed the real wiring, which is SHORTHAND
    // (`{ onLegacyAadRecord }`) rather than `onLegacyAadRecord:`, so it would
    // have blocked retirement for ever once draining worked. Stripping comments
    // and matching the bare name fixes both directions.
    const { readdirSync, statSync } = await import('node:fs');
    const sourcesUnder = (dir: string, out: string[] = []): string[] => {
      for (const entry of readdirSync(dir)) {
        const full = resolve(dir, entry);
        if (statSync(full).isDirectory()) {
          if (['node_modules', 'dist', '__tests__'].includes(entry)) continue;
          sourcesUnder(full, out);
          continue;
        }
        if (entry.endsWith('.ts') && !entry.endsWith('.test.ts')) out.push(full);
      }
      return out;
    };

    // ⚠ THE BRIDGE IS NOT IN THIS LIST, AND THAT IS THE DECISION RATHER THAN AN
    // OVERSIGHT. It never shipped, so no record was ever sealed under v1 by it
    // — there is no population to protect, and D-148 I-20 ("pre-launch
    // zero-installs: no migration code, no compat shims") says a shim guarding
    // nobody does not get written. Its store has no v1 reader at all; a guard
    // demanding one would be enforcing the opposite of the rule.
    //
    // ⛔ The webclient is different and stays: records sealed before its
    // migration exist, including the one this file opens two cases up.
    const surfaces = [
      {
        name: 'webclient',
        root: resolve(import.meta.dirname, '..'),
        store: resolve(import.meta.dirname, 'token-store.ts'),
      },
    ];

    for (const surface of surfaces) {
      const drains = sourcesUnder(surface.root)
        .filter((f) => f !== surface.store)
        .some((f) => codeOf(f).includes('onLegacyAadRecord'));

      if (drains) continue; // this surface converges; retirement is its own call

      const source = readFileSync(surface.store, 'utf-8');
      expect(
        source,
        `${surface.name} dropped its v1 reader while nothing re-seals there — every record sealed before the migration becomes unreadable`,
      ).toMatch(/const buildAadBytesV1\s*=/);
      expect(source, `${surface.name} declares a v1 reader it never calls`)
        .toMatch(/additional_data:\s*buildAadBytesV1\(/);
    }
  });

  /** ⛔ The bridge half of this claim lives in `token-aad-migration-bridge.test.ts`,
   *  NOT here. Omission from the public export is per FILE, and `apps/bridge` is
   *  not in that payload — keeping the assertion here forced a choice between
   *  dropping all thirteen of the above from public CI and shipping one that reds
   *  on a missing file. Put bridge-reading assertions in that file. */

  it('⚠ records which surfaces currently drain, so the answer is visible', async () => {
    // Not an assertion about what SHOULD drain — a statement of what does, so a
    // reader does not have to re-derive it from two file trees.
    const webclientDrains = codeOf(
      resolve(import.meta.dirname, '..', 'webclient-main.ts'),
    ).includes('onLegacyAadRecord');
    expect(webclientDrains, 'the webclient stopped re-sealing').toBe(true);
  });
});
